"""Internationalised UI strings.

One big dict keyed by language, then by message id. Missing keys fall back
to English (the project's default). Looked up via :func:`t`.

Language resolution order (highest wins):
  1. ``CLAUDE_USAGE_LANG`` env var
  2. ``lang`` field from settings.json
  3. System locale (``locale.getdefaultlocale()``)
  4. ``DEFAULT_LANG``
"""

from __future__ import annotations

import locale
import os
import sys
from typing import Any

DEFAULT_LANG = "en"
SUPPORTED_LANGS = ("en", "fr", "es", "de", "ja", "pt")

# Format placeholders use str.format syntax (``{name}``).
# Keep keys stable — they're referenced from other modules.
STRINGS: dict[str, dict[str, str]] = {
    "fr": {
        # menu items / static
        "not_connected": "non connecté",
        "login_item": "Se connecter à Claude Code",
        "quit": "Quitter",
        "refresh_never": "Rafraîchir  (jamais)",
        "refresh_pending": "Rafraîchir  (…)",
        "refresh_ts": "Rafraîchir  ({ts})",
        "refresh_fail": "Rafraîchir  (échec {ts})",
        "rate_limited": "Rate-limited  (retry dans {d})",
        "open_settings_tip": "Ouvrir {url}",
        "edit_settings": "Réglages…",
        "clear_alerts": "Désactiver les alertes actives",
        "menu_options": "Options",
        # updates
        "update_available": "Mise à jour disponible (v{ver})",
        "update_confirm_title": "Mettre à jour Claude Usage Tab ?",
        "update_confirm_body": "La version v{ver} va être installée (git pull puis réinstallation). Un terminal s'ouvrira et l'indicateur redémarrera.",
        "update_notif_title": "Mise à jour disponible",
        "update_notif_body": "Claude Usage Tab v{ver} est disponible — ouvre les Réglages ▸ Maintenance pour l'installer.",
        "update_spawn_fail_title": "Impossible de lancer la mise à jour",
        "update_spawn_fail_body": "Aucun terminal trouvé. Mets à jour à la main : git pull puis ./install.sh",
        # windows tray
        "win_startup": "Lancer au démarrage de Windows",
        "win_update_manual": "Impossible de lancer PowerShell. Mets à jour à la main : git pull puis .\\install-windows.ps1",
        # settings dialog
        "dlg_title": "Réglages — Claude Usage",
        "dlg_tab_general": "Général",
        "dlg_tab_topbar": "Top-bar",
        "dlg_lang": "Langue",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Rafraîchissement (s)",
        "dlg_thresholds": "Seuils d'alerte (%)",
        "dlg_thresholds_hint": "Séparés par des virgules, ex. 80, 95",
        "dlg_show_claude": "Afficher Claude dans la top-bar",
        "dlg_metric_five_hour": "Session 5h",
        "dlg_metric_seven_day": "Hebdo 7j",
        "dlg_metric_seven_day_sonnet": "Sonnet 7j",
        "dlg_provider_prefix": "Afficher le préfixe (C)",
        "dlg_alert_prefix": "Afficher le préfixe d'alerte (/!\\)",
        "dlg_metric_labels": "Étiqueter chaque métrique (5h, 7j)",
        "dlg_compact": "Mode compact (une seule valeur)",
        "dlg_metric_separator": "Séparateur entre métriques",
        "dlg_percent_decimals": "Décimales du pourcentage",
        "dlg_tab_accounts": "Comptes",
        "dlg_accounts_enabled": "Gérer plusieurs comptes Claude",
        "dlg_accounts_enabled_hint": "Mémorise chaque compte quand tu te connectes et affiche leur usage dans le menu.",
        "dlg_account_switch_enabled": "Autoriser le changement de compte (écrit ~/.claude)",
        "dlg_account_switch_hint": "Réécrit les identifiants de Claude Code. Effet au prochain lancement de `claude` ; peut perturber une session en cours.",
        "dlg_preview": "Aperçu :",
        "dlg_preview_icon_only": "(icône seule)",
        "dlg_save": "Enregistrer",
        "dlg_cancel": "Annuler",
        "dlg_edit_json": "Éditer le JSON (alertes…)",
        "dlg_save_failed_title": "Échec de l'enregistrement",
        # maintenance tab + update footer
        "dlg_tab_maintenance": "Maintenance",
        "dlg_version": "Version : {ver}",
        "dlg_update_uptodate": "Vous êtes à jour.",
        "dlg_update_available": "Mise à jour disponible : v{ver}",
        "dlg_update_btn": "Mettre à jour",
        "dlg_sound_menu": "Son (80 %)",
        "dlg_tab_sound": "Son",
        "dlg_sound_enabled": "Activer le son à 80 % (session)",
        "dlg_sound_mode": "Effet",
        "dlg_sound_mode_kylian": "Kylian dictateur",
        "dlg_sound_mode_classic": "Rappel classique",
        "dlg_sound_mode_custom": "Personnalisé",
        "dlg_sound_custom_audio": "Son personnalisé",
        "dlg_sound_custom_image": "Image personnalisée",
        "dlg_sound_choose_audio": "Choisir le son…",
        "dlg_sound_choose_image": "Choisir l'image…",
        "dlg_sound_test": "Tester l'alerte",
        "dlg_sound_none": "(aucun)",
        "dlg_update_check_enabled": "Vérifier les mises à jour au lancement",
        "dlg_update_check_hint": "Interroge l'API publique GitHub (aucune donnée ni token envoyés).",
        "dlg_uninstall_btn": "Désinstaller l'application…",
        "dlg_uninstall_confirm_title": "Désinstaller Claude Usage Tab ?",
        "dlg_uninstall_confirm_body": "Retire l'indicateur, l'entrée de démarrage automatique et les icônes. Un terminal s'ouvrira et l'indicateur s'arrêtera.",
        "dlg_uninstall_purge_check": "Supprimer aussi mes réglages, l'historique et les comptes stockés",
        "dlg_footer_uptodate": "v{ver} — à jour",
        "dlg_footer_update": "Mise à jour disponible (v{ver})",
        # metrics
        "session_5h": "5h",
        "weekly_7d": "7j",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7j  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7j  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        # multi-account (dropdown submenu)
        "accounts_menu": "Comptes Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7j {seven:.0f}%",
        "acct_usage_expired": "token expiré — bascule pour rafraîchir",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "indisponible",
        "acct_switch": "Basculer sur ce compte",
        "acct_switch_active": "Compte actif",
        "acct_switch_disabled": "Changement désactivé (voir Réglages)",
        "acct_forget": "Oublier ce compte",
        "acct_switch_confirm_title": "Basculer de compte Claude ?",
        "acct_switch_confirm_body": "Claude Code utilisera {email} au prochain lancement de `claude`. Une session déjà ouverte ne changera pas à chaud.",
        "acct_switch_ok_title": "Compte Claude changé",
        "acct_switch_ok_body": "{email} sera utilisé au prochain lancement de `claude`.",
        "acct_switch_fail_title": "Échec du changement de compte",
        "acct_switch_fail_body": "Impossible d'écrire les identifiants (permissions de ~/.claude ?).",
        "acct_forget_confirm_title": "Oublier ce compte ?",
        "acct_forget_confirm_body": "{email} sera retiré de la liste et ses identifiants stockés supprimés (aucun effet sur ~/.claude).",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "Coût API — {amount} aujourd'hui",
        "cost_menu_pending": "Coût API — …",
        "cost_today": "Aujourd'hui : {amount}",
        "cost_7d": "7 derniers jours : {amount}",
        "cost_month": "Ce mois-ci : {amount}",
        "cost_checked": "Mis à jour {when}",
        "cost_stale": "Dernier calcul en échec — valeurs précédentes",
        "cost_refresh": "Recalculer maintenant",
        "cost_pending": "Calcul en cours…",
        "dlg_cost_section": "Coût API (ccusage)",
        "dlg_cost_enabled": "Afficher le coût API dans le menu",
        "dlg_cost_command": "Commande (vide = détection auto)",
        "dlg_cost_refresh": "Rafraîchir toutes les (min)",
        "dlg_cost_hint": "Estimé par ccusage depuis les transcripts locaux — tous agents CLI confondus, ce n'est pas une facture.",
        "dlg_cost_detected": "Détecté : {cmd}",
        "dlg_cost_missing": "Aucun runner trouvé — installe bun, node ou pnpm",
        # notifications
        "login_title_ok": "Claude Code",
        "login_body_ok": "Termine le login OAuth dans le terminal qui vient de s'ouvrir.",
        "login_title_fail": "Se connecter à Claude Code",
        "login_body_fail": "Aucun terminal trouvé. Ouvre-en un et tape `claude`.",
        "reset_title": "{label} réinitialisée",
        "reset_body": "Compteur revenu à zéro.",
        "threshold_title": "{label} à {util:.0f}%",
        "threshold_body": "Reset {abs} (dans {rem})",
        "settings_reloaded_title": "Réglages rechargés",
        "settings_reloaded_body": "Le fichier de config a été appliqué.",
        "alert_fired_title": "Alerte : {label}",
        "alert_fired_body": "+{delta:.1f} pp sur {window}h ({metric})",
        # durations / format_remaining
        "now": "maintenant",
        "dash": "–",
        "duration_days_hours": "{d}j {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        # labels used in top-bar (composed in code by topbar.py)
        # ``label_guide`` is the width-reservation guide string; the
        # status segments below are the non-"ok" states (the ok segment is
        # built dynamically from the selected metrics).
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " non connecté ",
        # date format for strftime
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Terminaux Claude ({n})",
        "att_state_waiting": "attend une réponse",
        "att_state_done": "tâche terminée",
        "att_session": "{project} — {state}",
        "att_clear": "Arrêter le clignotement",
        "att_tip_waiting": "{n} en attente de réponse",
        "att_tip_done": "{n} terminée(s)",
        "dlg_att_section": "Terminaux Claude",
        "dlg_att_enabled": "Clignoter quand un terminal m'attend",
        "dlg_att_hooks_install": "Installer les hooks Claude Code",
        "dlg_att_hooks_remove": "Retirer les hooks Claude Code",
        "dlg_att_hooks_ok": "Hooks installés",
        "dlg_att_hooks_missing": "Hooks absents — le clignotement reste inactif",
        "dlg_att_hooks_confirm_title": "Installer les hooks Claude Code ?",
        "dlg_att_hooks_confirm_body": "Quatre hooks (Stop, Notification, UserPromptSubmit, SessionEnd) vont être ajoutés à ~/.claude/settings.json. Tes hooks existants ne sont pas modifiés et une sauvegarde est écrite dans settings.json.cusi-bak.",
        "dlg_att_hooks_failed": "Échec : {err}",
        "dlg_att_hint": "Les hooks déposent un témoin par session dans le cache ; l'icône clignote tant qu'un terminal attend.",
        "dlg_att_blink_ms": "Cadence du clignotement (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "Une session Claude tourne encore",
        "ho_busy_body": "{n} session(s) Claude Code sont ouvertes. La reprise fonctionnera quand même : une session vivante garde son jeton en mémoire. En revanche elle peut réécrire le fichier d'identifiants plus tard, et un prochain lancement repartirait alors sur l'ancien compte. Ferme-la quand tu peux.",
        "ho_unknown_body": "Impossible de vérifier si une session Claude est ouverte. La reprise fonctionnera, mais une session restée ouverte peut réécrire le fichier d'identifiants plus tard.",
        "ho_switch_anyway": "Continuer",
        "ho_resume_menu": "Basculer et reprendre dans…",
        "ho_no_projects": "Aucun projet récent",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "Basculer sur {email} et reprendre ?",
        "ho_resume_confirm_body": "Le compte actif deviendra {email}, puis un terminal s'ouvrira sur {project} avec claude --continue pour reprendre la dernière conversation de ce dossier.",
        "ho_resume_ok_title": "Bascule effectuée",
        "ho_resume_ok_body": "Terminal ouvert sur {project} avec le compte {email}.",
        "ho_no_binary_title": "Binaire claude introuvable",
        "ho_no_binary_body": "Impossible de localiser l'exécutable claude. La bascule a bien eu lieu, lance claude --continue toi-même.",
        "ho_launch_fail_title": "Impossible d'ouvrir un terminal",
        "ho_launch_fail_body": "La bascule a bien eu lieu, mais le terminal n'a pas pu être lancé. Lance claude --continue dans {project}.",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "Limite atteinte — basculer sur {email} et reprendre {project}",
        "ho_offer_title": "Limite 5 h atteinte",
        "ho_offer_body": "{email} a encore de la place ({util} %). Ouvre le menu pour basculer et reprendre {project}.",
    },
    "en": {
        "not_connected": "not signed in",
        "login_item": "Sign in to Claude Code",
        "quit": "Quit",
        "refresh_never": "Refresh  (never)",
        "refresh_pending": "Refresh  (…)",
        "refresh_ts": "Refresh  ({ts})",
        "refresh_fail": "Refresh  (failed {ts})",
        "rate_limited": "Rate-limited  (retry in {d})",
        "open_settings_tip": "Open {url}",
        "edit_settings": "Settings…",
        "clear_alerts": "Clear active alerts",
        "menu_options": "Options",
        # updates
        "update_available": "Update available (v{ver})",
        "update_confirm_title": "Update Claude Usage Tab?",
        "update_confirm_body": "Version v{ver} will be installed (git pull, then reinstall). A terminal will open and the indicator will restart.",
        "update_notif_title": "Update available",
        "update_notif_body": "Claude Usage Tab v{ver} is available — open Settings ▸ Maintenance to install it.",
        "update_spawn_fail_title": "Could not launch the update",
        "update_spawn_fail_body": "No terminal found. Update manually: git pull, then ./install.sh",
        # windows tray
        "win_startup": "Start with Windows",
        "win_update_manual": "Could not launch PowerShell. Update manually: git pull, then .\\install-windows.ps1",
        # settings dialog
        "dlg_title": "Settings — Claude Usage",
        "dlg_tab_general": "General",
        "dlg_tab_topbar": "Top-bar",
        "dlg_lang": "Language",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Refresh (s)",
        "dlg_thresholds": "Alert thresholds (%)",
        "dlg_thresholds_hint": "Comma-separated, e.g. 80, 95",
        "dlg_show_claude": "Show Claude in the top-bar",
        "dlg_metric_five_hour": "5h session",
        "dlg_metric_seven_day": "7-day weekly",
        "dlg_metric_seven_day_sonnet": "Sonnet 7-day",
        "dlg_provider_prefix": "Show prefix (C)",
        "dlg_alert_prefix": "Show alert prefix (/!\\)",
        "dlg_metric_labels": "Label each metric (5h, 7d)",
        "dlg_compact": "Compact mode (one value only)",
        "dlg_metric_separator": "Separator between metrics",
        "dlg_percent_decimals": "Percent decimals",
        "dlg_tab_accounts": "Accounts",
        "dlg_accounts_enabled": "Manage multiple Claude accounts",
        "dlg_accounts_enabled_hint": "Remembers each account when you sign in and shows their usage in the menu.",
        "dlg_account_switch_enabled": "Allow switching accounts (writes ~/.claude)",
        "dlg_account_switch_hint": "Rewrites Claude Code credentials. Takes effect on the next `claude` launch; may disrupt a running session.",
        "dlg_preview": "Preview:",
        "dlg_preview_icon_only": "(icon only)",
        "dlg_save": "Save",
        "dlg_cancel": "Cancel",
        "dlg_edit_json": "Edit JSON (alerts…)",
        "dlg_save_failed_title": "Could not save settings",
        # maintenance tab + update footer
        "dlg_tab_maintenance": "Maintenance",
        "dlg_version": "Version: {ver}",
        "dlg_update_uptodate": "You're up to date.",
        "dlg_update_available": "Update available: v{ver}",
        "dlg_update_btn": "Update now",
        "dlg_sound_menu": "Sound (80%)",
        "dlg_tab_sound": "Sound",
        "dlg_sound_enabled": "Enable 80% sound (session)",
        "dlg_sound_mode": "Effect",
        "dlg_sound_mode_kylian": "Kylian dictator",
        "dlg_sound_mode_classic": "Classic reminder",
        "dlg_sound_mode_custom": "Custom",
        "dlg_sound_custom_audio": "Custom sound",
        "dlg_sound_custom_image": "Custom image",
        "dlg_sound_choose_audio": "Choose sound…",
        "dlg_sound_choose_image": "Choose image…",
        "dlg_sound_test": "Test the alert",
        "dlg_sound_none": "(none)",
        "dlg_update_check_enabled": "Check for updates at launch",
        "dlg_update_check_hint": "Queries the public GitHub API (no data or token sent).",
        "dlg_uninstall_btn": "Uninstall the app…",
        "dlg_uninstall_confirm_title": "Uninstall Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Removes the indicator, its autostart entry and its icons. A terminal will open and the indicator will stop.",
        "dlg_uninstall_purge_check": "Also delete my settings, history and stored accounts",
        "dlg_footer_uptodate": "v{ver} — up to date",
        "dlg_footer_update": "Update available (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        # multi-account (dropdown submenu)
        "accounts_menu": "Claude accounts",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token expired — switch to refresh",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "unavailable",
        "acct_switch": "Switch to this account",
        "acct_switch_active": "Active account",
        "acct_switch_disabled": "Switching disabled (see Settings)",
        "acct_forget": "Forget this account",
        "acct_switch_confirm_title": "Switch Claude account?",
        "acct_switch_confirm_body": "Claude Code will use {email} on the next `claude` launch. A running session won't switch live.",
        "acct_switch_ok_title": "Claude account switched",
        "acct_switch_ok_body": "{email} will be used on the next `claude` launch.",
        "acct_switch_fail_title": "Account switch failed",
        "acct_switch_fail_body": "Could not write credentials (~/.claude permissions?).",
        "acct_forget_confirm_title": "Forget this account?",
        "acct_forget_confirm_body": "{email} will be removed from the list and its stored credentials deleted (no effect on ~/.claude).",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "API cost — {amount} today",
        "cost_menu_pending": "API cost — …",
        "cost_today": "Today: {amount}",
        "cost_7d": "Last 7 days: {amount}",
        "cost_month": "This month: {amount}",
        "cost_checked": "Updated {when}",
        "cost_stale": "Last refresh failed — showing last known",
        "cost_refresh": "Recalculate now",
        "cost_pending": "Calculating…",
        "dlg_cost_section": "API cost (ccusage)",
        "dlg_cost_enabled": "Show API cost in the menu",
        "dlg_cost_command": "Command (empty = auto-detect)",
        "dlg_cost_refresh": "Refresh every (min)",
        "dlg_cost_hint": "Estimated by ccusage from local transcripts — all CLI agents, not a bill.",
        "dlg_cost_detected": "Detected: {cmd}",
        "dlg_cost_missing": "No runner found — install bun, node or pnpm",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Finish the OAuth login in the terminal that just opened.",
        "login_title_fail": "Sign in to Claude Code",
        "login_body_fail": "No terminal found. Open one and run `claude`.",
        "reset_title": "{label} reset",
        "reset_body": "Counter back to zero.",
        "threshold_title": "{label} at {util:.0f}%",
        "threshold_body": "Resets {abs} (in {rem})",
        "settings_reloaded_title": "Settings reloaded",
        "settings_reloaded_body": "Config file applied.",
        "alert_fired_title": "Alert: {label}",
        "alert_fired_body": "+{delta:.1f} pp over {window}h ({metric})",
        "now": "now",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " not signed in ",
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Claude terminals ({n})",
        "att_state_waiting": "waiting for an answer",
        "att_state_done": "turn finished",
        "att_session": "{project} — {state}",
        "att_clear": "Stop blinking",
        "att_tip_waiting": "{n} waiting for an answer",
        "att_tip_done": "{n} finished",
        "dlg_att_section": "Claude terminals",
        "dlg_att_enabled": "Blink when a terminal wants me",
        "dlg_att_hooks_install": "Install the Claude Code hooks",
        "dlg_att_hooks_remove": "Remove the Claude Code hooks",
        "dlg_att_hooks_ok": "Hooks installed",
        "dlg_att_hooks_missing": "Hooks missing - blinking stays off",
        "dlg_att_hooks_confirm_title": "Install the Claude Code hooks?",
        "dlg_att_hooks_confirm_body": "Four hooks (Stop, Notification, UserPromptSubmit, SessionEnd) will be added to ~/.claude/settings.json. Your existing hooks are left untouched and a backup is written to settings.json.cusi-bak.",
        "dlg_att_hooks_failed": "Failed: {err}",
        "dlg_att_hint": "The hooks drop one flag per session in the cache; the icon blinks while a terminal is waiting.",
        "dlg_att_blink_ms": "Blink cadence (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "A Claude session is still running",
        "ho_busy_body": "{n} Claude Code session(s) are open. The resume will work anyway: a live session keeps its token in memory. It can, however, rewrite the credentials file later, and a future launch would then start on the old account. Close it when you can.",
        "ho_unknown_body": "Could not check whether a Claude session is open. The resume will work, but a session left open can rewrite the credentials file later.",
        "ho_switch_anyway": "Continue",
        "ho_resume_menu": "Switch and resume in…",
        "ho_no_projects": "No recent project",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "Switch to {email} and resume?",
        "ho_resume_confirm_body": "The active account becomes {email}, then a terminal opens in {project} running claude --continue to pick up that folder's last conversation.",
        "ho_resume_ok_title": "Switched",
        "ho_resume_ok_body": "Terminal opened in {project} with account {email}.",
        "ho_no_binary_title": "claude binary not found",
        "ho_no_binary_body": "Could not locate the claude executable. The switch went through; run claude --continue yourself.",
        "ho_launch_fail_title": "Could not open a terminal",
        "ho_launch_fail_body": "The switch went through, but the terminal could not be launched. Run claude --continue in {project}.",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "Limit reached — switch to {email} and resume {project}",
        "ho_offer_title": "5 h limit reached",
        "ho_offer_body": "{email} still has room ({util} %). Open the menu to switch and resume {project}.",
    },
    "es": {
        "not_connected": "sin sesión",
        "login_item": "Iniciar sesión en Claude Code",
        "quit": "Salir",
        "refresh_never": "Actualizar  (nunca)",
        "refresh_pending": "Actualizar  (…)",
        "refresh_ts": "Actualizar  ({ts})",
        "refresh_fail": "Actualizar  (error {ts})",
        "rate_limited": "Rate-limited  (reintento en {d})",
        "open_settings_tip": "Abrir {url}",
        "edit_settings": "Ajustes…",
        "clear_alerts": "Desactivar las alertas activas",
        "menu_options": "Opciones",
        "update_available": "Actualización disponible (v{ver})",
        "update_confirm_title": "¿Actualizar Claude Usage Tab?",
        "update_confirm_body": "Se instalará la versión v{ver} (git pull y reinstalación). Se abrirá una terminal y el indicador se reiniciará.",
        "update_notif_title": "Actualización disponible",
        "update_notif_body": "Claude Usage Tab v{ver} está disponible — abre Ajustes ▸ Mantenimiento para instalarla.",
        "update_spawn_fail_title": "No se pudo iniciar la actualización",
        "update_spawn_fail_body": "No se encontró ninguna terminal. Actualiza a mano: git pull y ./install.sh",
        # windows tray
        "win_startup": "Iniciar con Windows",
        "win_update_manual": "No se pudo abrir PowerShell. Actualiza a mano: git pull y .\\install-windows.ps1",
        "dlg_title": "Ajustes — Claude Usage",
        "dlg_tab_general": "General",
        "dlg_tab_topbar": "Barra superior",
        "dlg_lang": "Idioma",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Actualización (s)",
        "dlg_thresholds": "Umbrales de alerta (%)",
        "dlg_thresholds_hint": "Separados por comas, p. ej. 80, 95",
        "dlg_show_claude": "Mostrar Claude en la barra superior",
        "dlg_metric_five_hour": "Sesión 5h",
        "dlg_metric_seven_day": "Semanal 7d",
        "dlg_metric_seven_day_sonnet": "Sonnet 7d",
        "dlg_provider_prefix": "Mostrar el prefijo (C)",
        "dlg_alert_prefix": "Mostrar el prefijo de alerta (/!\\)",
        "dlg_metric_labels": "Etiquetar cada métrica (5h, 7d)",
        "dlg_compact": "Modo compacto (un solo valor)",
        "dlg_metric_separator": "Separador entre métricas",
        "dlg_percent_decimals": "Decimales del porcentaje",
        "dlg_tab_accounts": "Cuentas",
        "dlg_accounts_enabled": "Gestionar varias cuentas de Claude",
        "dlg_accounts_enabled_hint": "Recuerda cada cuenta cuando inicias sesión y muestra su uso en el menú.",
        "dlg_account_switch_enabled": "Permitir cambiar de cuenta (escribe ~/.claude)",
        "dlg_account_switch_hint": "Reescribe las credenciales de Claude Code. Surte efecto en el próximo arranque de `claude`; puede afectar una sesión en curso.",
        "dlg_preview": "Vista previa:",
        "dlg_preview_icon_only": "(solo icono)",
        "dlg_save": "Guardar",
        "dlg_cancel": "Cancelar",
        "dlg_edit_json": "Editar JSON (alertas…)",
        "dlg_save_failed_title": "No se pudieron guardar los ajustes",
        "dlg_tab_maintenance": "Mantenimiento",
        "dlg_version": "Versión: {ver}",
        "dlg_update_uptodate": "Estás al día.",
        "dlg_update_available": "Actualización disponible: v{ver}",
        "dlg_update_btn": "Actualizar",
        "dlg_sound_menu": "Sonido (80 %)",
        "dlg_tab_sound": "Sonido",
        "dlg_sound_enabled": "Activar sonido al 80 % (sesión)",
        "dlg_sound_mode": "Efecto",
        "dlg_sound_mode_kylian": "Kylian dictador",
        "dlg_sound_mode_classic": "Recordatorio clásico",
        "dlg_sound_mode_custom": "Personalizado",
        "dlg_sound_custom_audio": "Sonido personalizado",
        "dlg_sound_custom_image": "Imagen personalizada",
        "dlg_sound_choose_audio": "Elegir sonido…",
        "dlg_sound_choose_image": "Elegir imagen…",
        "dlg_sound_test": "Probar la alerta",
        "dlg_sound_none": "(ninguno)",
        "dlg_update_check_enabled": "Buscar actualizaciones al iniciar",
        "dlg_update_check_hint": "Consulta la API pública de GitHub (no se envía ningún dato ni token).",
        "dlg_uninstall_btn": "Desinstalar la aplicación…",
        "dlg_uninstall_confirm_title": "¿Desinstalar Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Elimina el indicador, su entrada de arranque automático y sus iconos. Se abrirá una terminal y el indicador se detendrá.",
        "dlg_uninstall_purge_check": "Eliminar también mis ajustes, el historial y las cuentas guardadas",
        "dlg_footer_uptodate": "v{ver} — al día",
        "dlg_footer_update": "Actualización disponible (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Cuentas de Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token caducado — cambia para actualizar",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "no disponible",
        "acct_switch": "Cambiar a esta cuenta",
        "acct_switch_active": "Cuenta activa",
        "acct_switch_disabled": "Cambio desactivado (ver Ajustes)",
        "acct_forget": "Olvidar esta cuenta",
        "acct_switch_confirm_title": "¿Cambiar de cuenta de Claude?",
        "acct_switch_confirm_body": "Claude Code usará {email} en el próximo arranque de `claude`. Una sesión ya abierta no cambiará en caliente.",
        "acct_switch_ok_title": "Cuenta de Claude cambiada",
        "acct_switch_ok_body": "{email} se usará en el próximo arranque de `claude`.",
        "acct_switch_fail_title": "Error al cambiar de cuenta",
        "acct_switch_fail_body": "No se pudieron escribir las credenciales (¿permisos de ~/.claude?).",
        "acct_forget_confirm_title": "¿Olvidar esta cuenta?",
        "acct_forget_confirm_body": "{email} se quitará de la lista y sus credenciales guardadas se borrarán (sin efecto en ~/.claude).",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "Coste API — {amount} hoy",
        "cost_menu_pending": "Coste API — …",
        "cost_today": "Hoy: {amount}",
        "cost_7d": "Últimos 7 días: {amount}",
        "cost_month": "Este mes: {amount}",
        "cost_checked": "Actualizado {when}",
        "cost_stale": "El último cálculo falló — valores anteriores",
        "cost_refresh": "Recalcular ahora",
        "cost_pending": "Calculando…",
        "dlg_cost_section": "Coste API (ccusage)",
        "dlg_cost_enabled": "Mostrar el coste API en el menú",
        "dlg_cost_command": "Comando (vacío = detección automática)",
        "dlg_cost_refresh": "Actualizar cada (min)",
        "dlg_cost_hint": "Estimado por ccusage desde los transcripts locales — todos los agentes CLI, no es una factura.",
        "dlg_cost_detected": "Detectado: {cmd}",
        "dlg_cost_missing": "Ningún runner encontrado — instala bun, node o pnpm",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Termina el inicio de sesión OAuth en la terminal que se acaba de abrir.",
        "login_title_fail": "Iniciar sesión en Claude Code",
        "login_body_fail": "No se encontró ninguna terminal. Abre una y ejecuta `claude`.",
        "reset_title": "{label} reiniciada",
        "reset_body": "Contador de vuelta a cero.",
        "threshold_title": "{label} al {util:.0f}%",
        "threshold_body": "Se reinicia {abs} (en {rem})",
        "settings_reloaded_title": "Ajustes recargados",
        "settings_reloaded_body": "Se aplicó el archivo de configuración.",
        "alert_fired_title": "Alerta: {label}",
        "alert_fired_body": "+{delta:.1f} pp en {window}h ({metric})",
        "now": "ahora",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " sin sesión ",
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Terminales Claude ({n})",
        "att_state_waiting": "espera una respuesta",
        "att_state_done": "tarea terminada",
        "att_session": "{project} — {state}",
        "att_clear": "Detener el parpadeo",
        "att_tip_waiting": "{n} esperando respuesta",
        "att_tip_done": "{n} terminada(s)",
        "dlg_att_section": "Terminales Claude",
        "dlg_att_enabled": "Parpadear cuando un terminal me espera",
        "dlg_att_hooks_install": "Instalar los hooks de Claude Code",
        "dlg_att_hooks_remove": "Quitar los hooks de Claude Code",
        "dlg_att_hooks_ok": "Hooks instalados",
        "dlg_att_hooks_missing": "Faltan los hooks — el parpadeo sigue inactivo",
        "dlg_att_hooks_confirm_title": "¿Instalar los hooks de Claude Code?",
        "dlg_att_hooks_confirm_body": "Se añadirán cuatro hooks (Stop, Notification, UserPromptSubmit, SessionEnd) a ~/.claude/settings.json. Tus hooks actuales no se modifican y se guarda una copia en settings.json.cusi-bak.",
        "dlg_att_hooks_failed": "Error: {err}",
        "dlg_att_hint": "Los hooks escriben un testigo por sesión en la caché; el icono parpadea mientras un terminal espera.",
        "dlg_att_blink_ms": "Cadencia del parpadeo (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "Todavía hay una sesión de Claude abierta",
        "ho_busy_body": "Hay {n} sesión(es) de Claude Code abiertas. La reanudación funcionará igualmente: una sesión viva conserva su token en memoria. Pero puede reescribir el archivo de credenciales más tarde, y un próximo arranque usaría la cuenta anterior. Ciérrala cuando puedas.",
        "ho_unknown_body": "No se pudo comprobar si hay una sesión de Claude abierta. La reanudación funcionará, pero una sesión abierta puede reescribir el archivo de credenciales más tarde.",
        "ho_switch_anyway": "Continuar",
        "ho_resume_menu": "Cambiar y reanudar en…",
        "ho_no_projects": "Ningún proyecto reciente",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "¿Cambiar a {email} y reanudar?",
        "ho_resume_confirm_body": "La cuenta activa pasará a ser {email} y se abrirá un terminal en {project} con claude --continue para retomar la última conversación de esa carpeta.",
        "ho_resume_ok_title": "Cambio realizado",
        "ho_resume_ok_body": "Terminal abierto en {project} con la cuenta {email}.",
        "ho_no_binary_title": "No se encuentra el binario claude",
        "ho_no_binary_body": "No se pudo localizar el ejecutable claude. El cambio se hizo; ejecuta claude --continue tú mismo.",
        "ho_launch_fail_title": "No se pudo abrir un terminal",
        "ho_launch_fail_body": "El cambio se hizo, pero no se pudo abrir el terminal. Ejecuta claude --continue en {project}.",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "Límite alcanzado — cambiar a {email} y reanudar {project}",
        "ho_offer_title": "Límite de 5 h alcanzado",
        "ho_offer_body": "{email} todavía tiene margen ({util} %). Abre el menú para cambiar y reanudar {project}.",
    },
    "de": {
        "not_connected": "nicht angemeldet",
        "login_item": "Bei Claude Code anmelden",
        "quit": "Beenden",
        "refresh_never": "Aktualisieren  (nie)",
        "refresh_pending": "Aktualisieren  (…)",
        "refresh_ts": "Aktualisieren  ({ts})",
        "refresh_fail": "Aktualisieren  (Fehler {ts})",
        "rate_limited": "Rate-limited  (erneut in {d})",
        "open_settings_tip": "{url} öffnen",
        "edit_settings": "Einstellungen…",
        "clear_alerts": "Aktive Warnungen deaktivieren",
        "menu_options": "Optionen",
        "update_available": "Update verfügbar (v{ver})",
        "update_confirm_title": "Claude Usage Tab aktualisieren?",
        "update_confirm_body": "Version v{ver} wird installiert (git pull, dann Neuinstallation). Ein Terminal öffnet sich und der Indikator startet neu.",
        "update_notif_title": "Update verfügbar",
        "update_notif_body": "Claude Usage Tab v{ver} ist verfügbar — öffne Einstellungen ▸ Wartung, um es zu installieren.",
        "update_spawn_fail_title": "Update konnte nicht gestartet werden",
        "update_spawn_fail_body": "Kein Terminal gefunden. Manuell aktualisieren: git pull, dann ./install.sh",
        # windows tray
        "win_startup": "Mit Windows starten",
        "win_update_manual": "PowerShell konnte nicht gestartet werden. Manuell aktualisieren: git pull, dann .\\install-windows.ps1",
        "dlg_title": "Einstellungen — Claude Usage",
        "dlg_tab_general": "Allgemein",
        "dlg_tab_topbar": "Menüleiste",
        "dlg_lang": "Sprache",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Aktualisierung (s)",
        "dlg_thresholds": "Warnschwellen (%)",
        "dlg_thresholds_hint": "Komma-getrennt, z. B. 80, 95",
        "dlg_show_claude": "Claude in der Menüleiste anzeigen",
        "dlg_metric_five_hour": "5h-Sitzung",
        "dlg_metric_seven_day": "Woche 7T",
        "dlg_metric_seven_day_sonnet": "Sonnet 7T",
        "dlg_provider_prefix": "Präfix anzeigen (C)",
        "dlg_alert_prefix": "Warn-Präfix anzeigen (/!\\)",
        "dlg_metric_labels": "Jede Metrik beschriften (5h, 7T)",
        "dlg_compact": "Kompaktmodus (nur ein Wert)",
        "dlg_metric_separator": "Trennzeichen zwischen Metriken",
        "dlg_percent_decimals": "Nachkommastellen (Prozent)",
        "dlg_tab_accounts": "Konten",
        "dlg_accounts_enabled": "Mehrere Claude-Konten verwalten",
        "dlg_accounts_enabled_hint": "Merkt sich jedes Konto beim Anmelden und zeigt dessen Nutzung im Menü.",
        "dlg_account_switch_enabled": "Kontowechsel erlauben (schreibt ~/.claude)",
        "dlg_account_switch_hint": "Überschreibt die Claude-Code-Anmeldedaten. Wirkt beim nächsten `claude`-Start; kann eine laufende Sitzung stören.",
        "dlg_preview": "Vorschau:",
        "dlg_preview_icon_only": "(nur Symbol)",
        "dlg_save": "Speichern",
        "dlg_cancel": "Abbrechen",
        "dlg_edit_json": "JSON bearbeiten (Warnungen…)",
        "dlg_save_failed_title": "Einstellungen konnten nicht gespeichert werden",
        "dlg_tab_maintenance": "Wartung",
        "dlg_version": "Version: {ver}",
        "dlg_update_uptodate": "Du bist auf dem neuesten Stand.",
        "dlg_update_available": "Update verfügbar: v{ver}",
        "dlg_update_btn": "Jetzt aktualisieren",
        "dlg_sound_menu": "Ton (80 %)",
        "dlg_tab_sound": "Ton",
        "dlg_sound_enabled": "Ton bei 80 % aktivieren (Sitzung)",
        "dlg_sound_mode": "Effekt",
        "dlg_sound_mode_kylian": "Kylian-Diktator",
        "dlg_sound_mode_classic": "Klassische Erinnerung",
        "dlg_sound_mode_custom": "Benutzerdefiniert",
        "dlg_sound_custom_audio": "Eigener Ton",
        "dlg_sound_custom_image": "Eigenes Bild",
        "dlg_sound_choose_audio": "Ton wählen…",
        "dlg_sound_choose_image": "Bild wählen…",
        "dlg_sound_test": "Alarm testen",
        "dlg_sound_none": "(keiner)",
        "dlg_update_check_enabled": "Beim Start nach Updates suchen",
        "dlg_update_check_hint": "Fragt die öffentliche GitHub-API ab (keine Daten oder Tokens gesendet).",
        "dlg_uninstall_btn": "App deinstallieren…",
        "dlg_uninstall_confirm_title": "Claude Usage Tab deinstallieren?",
        "dlg_uninstall_confirm_body": "Entfernt den Indikator, seinen Autostart-Eintrag und seine Symbole. Ein Terminal öffnet sich und der Indikator wird beendet.",
        "dlg_uninstall_purge_check": "Auch meine Einstellungen, den Verlauf und gespeicherte Konten löschen",
        "dlg_footer_uptodate": "v{ver} — aktuell",
        "dlg_footer_update": "Update verfügbar (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7T",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7T  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7T  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Claude-Konten",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7T {seven:.0f}%",
        "acct_usage_expired": "Token abgelaufen — wechseln zum Aktualisieren",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "nicht verfügbar",
        "acct_switch": "Zu diesem Konto wechseln",
        "acct_switch_active": "Aktives Konto",
        "acct_switch_disabled": "Wechsel deaktiviert (siehe Einstellungen)",
        "acct_forget": "Dieses Konto vergessen",
        "acct_switch_confirm_title": "Claude-Konto wechseln?",
        "acct_switch_confirm_body": "Claude Code verwendet {email} beim nächsten `claude`-Start. Eine bereits laufende Sitzung wechselt nicht live.",
        "acct_switch_ok_title": "Claude-Konto gewechselt",
        "acct_switch_ok_body": "{email} wird beim nächsten `claude`-Start verwendet.",
        "acct_switch_fail_title": "Kontowechsel fehlgeschlagen",
        "acct_switch_fail_body": "Anmeldedaten konnten nicht geschrieben werden (Rechte von ~/.claude?).",
        "acct_forget_confirm_title": "Dieses Konto vergessen?",
        "acct_forget_confirm_body": "{email} wird aus der Liste entfernt und die gespeicherten Anmeldedaten gelöscht (keine Auswirkung auf ~/.claude).",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "API-Kosten — heute {amount}",
        "cost_menu_pending": "API-Kosten — …",
        "cost_today": "Heute: {amount}",
        "cost_7d": "Letzte 7 Tage: {amount}",
        "cost_month": "Dieser Monat: {amount}",
        "cost_checked": "Aktualisiert {when}",
        "cost_stale": "Letzte Aktualisierung fehlgeschlagen — bekannte Werte",
        "cost_refresh": "Jetzt neu berechnen",
        "cost_pending": "Berechne…",
        "dlg_cost_section": "API-Kosten (ccusage)",
        "dlg_cost_enabled": "API-Kosten im Menü anzeigen",
        "dlg_cost_command": "Befehl (leer = automatisch erkennen)",
        "dlg_cost_refresh": "Aktualisieren alle (Min.)",
        "dlg_cost_hint": "Von ccusage aus lokalen Transcripts geschätzt — alle CLI-Agents, keine Rechnung.",
        "dlg_cost_detected": "Erkannt: {cmd}",
        "dlg_cost_missing": "Kein Runner gefunden — bun, node oder pnpm installieren",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Schließe die OAuth-Anmeldung im gerade geöffneten Terminal ab.",
        "login_title_fail": "Bei Claude Code anmelden",
        "login_body_fail": "Kein Terminal gefunden. Öffne eines und führe `claude` aus.",
        "reset_title": "{label} zurückgesetzt",
        "reset_body": "Zähler wieder auf null.",
        "threshold_title": "{label} bei {util:.0f}%",
        "threshold_body": "Zurücksetzung {abs} (in {rem})",
        "settings_reloaded_title": "Einstellungen neu geladen",
        "settings_reloaded_body": "Konfigurationsdatei angewendet.",
        "alert_fired_title": "Warnung: {label}",
        "alert_fired_body": "+{delta:.1f} pp über {window}h ({metric})",
        "now": "jetzt",
        "dash": "–",
        "duration_days_hours": "{d}T {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " nicht angemeldet ",
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Claude-Terminals ({n})",
        "att_state_waiting": "wartet auf eine Antwort",
        "att_state_done": "Aufgabe beendet",
        "att_session": "{project} — {state}",
        "att_clear": "Blinken beenden",
        "att_tip_waiting": "{n} warten auf Antwort",
        "att_tip_done": "{n} fertig",
        "dlg_att_section": "Claude-Terminals",
        "dlg_att_enabled": "Blinken, wenn ein Terminal wartet",
        "dlg_att_hooks_install": "Claude-Code-Hooks installieren",
        "dlg_att_hooks_remove": "Claude-Code-Hooks entfernen",
        "dlg_att_hooks_ok": "Hooks installiert",
        "dlg_att_hooks_missing": "Hooks fehlen — das Blinken bleibt aus",
        "dlg_att_hooks_confirm_title": "Claude-Code-Hooks installieren?",
        "dlg_att_hooks_confirm_body": "Vier Hooks (Stop, Notification, UserPromptSubmit, SessionEnd) werden zu ~/.claude/settings.json hinzugefügt. Deine vorhandenen Hooks bleiben unverändert, eine Sicherung landet in settings.json.cusi-bak.",
        "dlg_att_hooks_failed": "Fehlgeschlagen: {err}",
        "dlg_att_hint": "Die Hooks legen pro Sitzung eine Markierung im Cache ab; das Symbol blinkt, solange ein Terminal wartet.",
        "dlg_att_blink_ms": "Blinkfrequenz (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "Es läuft noch eine Claude-Sitzung",
        "ho_busy_body": "{n} Claude-Code-Sitzung(en) sind offen. Das Fortsetzen klappt trotzdem: eine laufende Sitzung behält ihr Token im Speicher. Sie kann die Zugangsdaten aber später überschreiben, und ein künftiger Start liefe dann auf dem alten Konto. Schließe sie, sobald es passt.",
        "ho_unknown_body": "Es ließ sich nicht prüfen, ob eine Claude-Sitzung offen ist. Das Fortsetzen klappt, doch eine offen gebliebene Sitzung kann die Zugangsdaten später überschreiben.",
        "ho_switch_anyway": "Weiter",
        "ho_resume_menu": "Wechseln und fortsetzen in…",
        "ho_no_projects": "Kein aktuelles Projekt",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "Zu {email} wechseln und fortsetzen?",
        "ho_resume_confirm_body": "Das aktive Konto wird {email}, dann öffnet sich ein Terminal in {project} mit claude --continue, um das letzte Gespräch dieses Ordners fortzusetzen.",
        "ho_resume_ok_title": "Gewechselt",
        "ho_resume_ok_body": "Terminal in {project} mit Konto {email} geöffnet.",
        "ho_no_binary_title": "claude-Binary nicht gefunden",
        "ho_no_binary_body": "Die claude-Datei wurde nicht gefunden. Der Wechsel hat geklappt; starte claude --continue selbst.",
        "ho_launch_fail_title": "Terminal konnte nicht geöffnet werden",
        "ho_launch_fail_body": "Der Wechsel hat geklappt, das Terminal ließ sich nicht starten. Führe claude --continue in {project} aus.",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "Limit erreicht — zu {email} wechseln und {project} fortsetzen",
        "ho_offer_title": "5-Stunden-Limit erreicht",
        "ho_offer_body": "{email} hat noch Luft ({util} %). Öffne das Menü, um zu wechseln und {project} fortzusetzen.",
    },
    "ja": {
        "not_connected": "未接続",
        "login_item": "Claude Code にサインイン",
        "quit": "終了",
        "refresh_never": "更新  (未実行)",
        "refresh_pending": "更新  (…)",
        "refresh_ts": "更新  ({ts})",
        "refresh_fail": "更新  (失敗 {ts})",
        "rate_limited": "Rate-limited  (再試行 {d})",
        "open_settings_tip": "{url} を開く",
        "edit_settings": "設定…",
        "clear_alerts": "有効なアラートを解除",
        "menu_options": "オプション",
        "update_available": "アップデートあり (v{ver})",
        "update_confirm_title": "Claude Usage Tab を更新しますか？",
        "update_confirm_body": "バージョン v{ver} をインストールします（git pull 後に再インストール）。ターミナルが開き、インジケーターが再起動します。",
        "update_notif_title": "アップデートあり",
        "update_notif_body": "Claude Usage Tab v{ver} が利用可能です — 設定 ▸ メンテナンス から更新できます。",
        "update_spawn_fail_title": "アップデートを起動できませんでした",
        "update_spawn_fail_body": "ターミナルが見つかりません。手動で更新してください: git pull 後に ./install.sh",
        # windows tray
        "win_startup": "Windows起動時に開始",
        "win_update_manual": "PowerShell を起動できません。手動で更新してください: git pull 後に .\\install-windows.ps1",
        "dlg_title": "設定 — Claude Usage",
        "dlg_tab_general": "一般",
        "dlg_tab_topbar": "メニューバー",
        "dlg_lang": "言語",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "更新間隔 (秒)",
        "dlg_thresholds": "アラートしきい値 (%)",
        "dlg_thresholds_hint": "カンマ区切り、例: 80, 95",
        "dlg_show_claude": "メニューバーに Claude を表示",
        "dlg_metric_five_hour": "5時間セッション",
        "dlg_metric_seven_day": "週間 7日",
        "dlg_metric_seven_day_sonnet": "Sonnet 7日",
        "dlg_provider_prefix": "接頭辞を表示 (C)",
        "dlg_alert_prefix": "アラート接頭辞を表示 (/!\\)",
        "dlg_metric_labels": "各指標にラベルを付ける (5h, 7d)",
        "dlg_compact": "コンパクト表示（1つの値のみ）",
        "dlg_metric_separator": "指標間の区切り文字",
        "dlg_percent_decimals": "パーセントの小数点以下桁数",
        "dlg_tab_accounts": "アカウント",
        "dlg_accounts_enabled": "複数の Claude アカウントを管理",
        "dlg_accounts_enabled_hint": "サインインするたびに各アカウントを記憶し、その使用状況をメニューに表示します。",
        "dlg_account_switch_enabled": "アカウント切り替えを許可 (~/.claude に書き込み)",
        "dlg_account_switch_hint": "Claude Code の認証情報を書き換えます。次回の `claude` 起動時に反映され、実行中のセッションに影響する場合があります。",
        "dlg_preview": "プレビュー:",
        "dlg_preview_icon_only": "(アイコンのみ)",
        "dlg_save": "保存",
        "dlg_cancel": "キャンセル",
        "dlg_edit_json": "JSON を編集 (アラート…)",
        "dlg_save_failed_title": "設定を保存できませんでした",
        "dlg_tab_maintenance": "メンテナンス",
        "dlg_version": "バージョン: {ver}",
        "dlg_update_uptodate": "最新の状態です。",
        "dlg_update_available": "アップデートあり: v{ver}",
        "dlg_update_btn": "今すぐ更新",
        "dlg_sound_menu": "通知音（80%）",
        "dlg_tab_sound": "通知音",
        "dlg_sound_enabled": "80% の通知音を有効化（セッション）",
        "dlg_sound_mode": "効果",
        "dlg_sound_mode_kylian": "キリアン独裁者",
        "dlg_sound_mode_classic": "クラシックな通知音",
        "dlg_sound_mode_custom": "カスタム",
        "dlg_sound_custom_audio": "カスタム音声",
        "dlg_sound_custom_image": "カスタム画像",
        "dlg_sound_choose_audio": "音声を選択…",
        "dlg_sound_choose_image": "画像を選択…",
        "dlg_sound_test": "アラートをテスト",
        "dlg_sound_none": "（なし）",
        "dlg_update_check_enabled": "起動時にアップデートを確認",
        "dlg_update_check_hint": "GitHub の公開 API に問い合わせます（データやトークンは送信しません）。",
        "dlg_uninstall_btn": "アプリをアンインストール…",
        "dlg_uninstall_confirm_title": "Claude Usage Tab をアンインストールしますか？",
        "dlg_uninstall_confirm_body": "インジケーター、自動起動エントリ、アイコンを削除します。ターミナルが開き、インジケーターが停止します。",
        "dlg_uninstall_purge_check": "設定・履歴・保存済みアカウントも削除する",
        "dlg_footer_uptodate": "v{ver} — 最新",
        "dlg_footer_update": "アップデートあり (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Claude アカウント",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "トークン期限切れ — 切り替えて更新",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "利用不可",
        "acct_switch": "このアカウントに切り替え",
        "acct_switch_active": "アクティブなアカウント",
        "acct_switch_disabled": "切り替えは無効です（設定を参照）",
        "acct_forget": "このアカウントを削除",
        "acct_switch_confirm_title": "Claude アカウントを切り替えますか？",
        "acct_switch_confirm_body": "次回の `claude` 起動時に Claude Code は {email} を使用します。実行中のセッションはその場では切り替わりません。",
        "acct_switch_ok_title": "Claude アカウントを切り替えました",
        "acct_switch_ok_body": "次回の `claude` 起動時に {email} が使用されます。",
        "acct_switch_fail_title": "アカウントの切り替えに失敗",
        "acct_switch_fail_body": "認証情報を書き込めませんでした（~/.claude の権限を確認）。",
        "acct_forget_confirm_title": "このアカウントを削除しますか？",
        "acct_forget_confirm_body": "{email} をリストから削除し、保存された認証情報を消去します（~/.claude には影響しません）。",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "API コスト — 本日 {amount}",
        "cost_menu_pending": "API コスト — …",
        "cost_today": "本日: {amount}",
        "cost_7d": "過去 7 日間: {amount}",
        "cost_month": "今月: {amount}",
        "cost_checked": "更新 {when}",
        "cost_stale": "前回の更新に失敗 — 最後に取得した値",
        "cost_refresh": "今すぐ再計算",
        "cost_pending": "計算中…",
        "dlg_cost_section": "API コスト (ccusage)",
        "dlg_cost_enabled": "メニューに API コストを表示",
        "dlg_cost_command": "コマンド (空欄 = 自動検出)",
        "dlg_cost_refresh": "更新間隔 (分)",
        "dlg_cost_hint": "ローカルのトランスクリプトから ccusage が推定 — 全 CLI エージェント合計。請求額ではありません。",
        "dlg_cost_detected": "検出: {cmd}",
        "dlg_cost_missing": "ランナーが見つかりません — bun / node / pnpm を導入",
        "login_title_ok": "Claude Code",
        "login_body_ok": "開いたターミナルで OAuth ログインを完了してください。",
        "login_title_fail": "Claude Code にサインイン",
        "login_body_fail": "ターミナルが見つかりません。ターミナルを開いて `claude` を実行してください。",
        "reset_title": "{label} をリセットしました",
        "reset_body": "カウンターがゼロに戻りました。",
        "threshold_title": "{label} が {util:.0f}%",
        "threshold_body": "リセット {abs}（{rem}後）",
        "settings_reloaded_title": "設定を再読み込みしました",
        "settings_reloaded_body": "設定ファイルを適用しました。",
        "alert_fired_title": "アラート: {label}",
        "alert_fired_body": "+{delta:.1f} pp / {window}h ({metric})",
        "now": "今",
        "dash": "–",
        "duration_days_hours": "{d}日{h}時間",
        "duration_hours_minutes": "{h}時間{m:02d}分",
        "duration_minutes": "{m}分",
        "duration_seconds": "{s}秒",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " 未接続 ",
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Claude ターミナル ({n})",
        "att_state_waiting": "応答待ち",
        "att_state_done": "タスク完了",
        "att_session": "{project} — {state}",
        "att_clear": "点滅を止める",
        "att_tip_waiting": "{n} 件が応答待ち",
        "att_tip_done": "{n} 件が完了",
        "dlg_att_section": "Claude ターミナル",
        "dlg_att_enabled": "ターミナルが待っているときにアイコンを点滅させる",
        "dlg_att_hooks_install": "Claude Code のフックをインストール",
        "dlg_att_hooks_remove": "Claude Code のフックを削除",
        "dlg_att_hooks_ok": "フックはインストール済み",
        "dlg_att_hooks_missing": "フックが未設定 — 点滅は無効のままです",
        "dlg_att_hooks_confirm_title": "Claude Code のフックをインストールしますか？",
        "dlg_att_hooks_confirm_body": "4 つのフック (Stop、Notification、UserPromptSubmit、SessionEnd) を ~/.claude/settings.json に追加します。既存のフックは変更せず、settings.json.cusi-bak にバックアップを作成します。",
        "dlg_att_hooks_failed": "失敗: {err}",
        "dlg_att_hint": "フックはセッションごとに目印をキャッシュへ書き込みます。ターミナルが待っている間、アイコンが点滅します。",
        "dlg_att_blink_ms": "点滅の間隔 (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "Claude のセッションがまだ動いています",
        "ho_busy_body": "Claude Code のセッションが {n} 件開いています。再開は問題なく動きます。動作中のセッションはトークンをメモリに保持しているためです。ただし後から認証情報ファイルを上書きすることがあり、その場合は次回の起動が以前のアカウントになります。落ち着いたら閉じてください。",
        "ho_unknown_body": "Claude のセッションが開いているか確認できませんでした。再開は動作しますが、開いたままのセッションが後で認証情報ファイルを上書きすることがあります。",
        "ho_switch_anyway": "続行",
        "ho_resume_menu": "切り替えて再開する…",
        "ho_no_projects": "最近のプロジェクトなし",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "{email} に切り替えて再開しますか？",
        "ho_resume_confirm_body": "有効なアカウントが {email} になり、{project} でターミナルが開いて claude --continue がそのフォルダーの直前の会話を再開します。",
        "ho_resume_ok_title": "切り替えました",
        "ho_resume_ok_body": "アカウント {email} で {project} のターミナルを開きました。",
        "ho_no_binary_title": "claude の実行ファイルが見つかりません",
        "ho_no_binary_body": "claude の実行ファイルを特定できませんでした。切り替えは完了しています。claude --continue をご自身で実行してください。",
        "ho_launch_fail_title": "ターミナルを開けませんでした",
        "ho_launch_fail_body": "切り替えは完了しましたが、ターミナルを起動できませんでした。{project} で claude --continue を実行してください。",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "上限に到達 — {email} に切り替えて {project} を再開",
        "ho_offer_title": "5 時間の上限に到達",
        "ho_offer_body": "{email} にはまだ余裕があります ({util} %)。メニューから切り替えて {project} を再開できます。",
    },
    "pt": {
        "not_connected": "sem sessão",
        "login_item": "Entrar no Claude Code",
        "quit": "Sair",
        "refresh_never": "Atualizar  (nunca)",
        "refresh_pending": "Atualizar  (…)",
        "refresh_ts": "Atualizar  ({ts})",
        "refresh_fail": "Atualizar  (falha {ts})",
        "rate_limited": "Rate-limited  (nova tentativa em {d})",
        "open_settings_tip": "Abrir {url}",
        "edit_settings": "Configurações…",
        "clear_alerts": "Desativar os alertas ativos",
        "menu_options": "Opções",
        "update_available": "Atualização disponível (v{ver})",
        "update_confirm_title": "Atualizar o Claude Usage Tab?",
        "update_confirm_body": "A versão v{ver} será instalada (git pull e reinstalação). Um terminal será aberto e o indicador reiniciará.",
        "update_notif_title": "Atualização disponível",
        "update_notif_body": "Claude Usage Tab v{ver} está disponível — abra Configurações ▸ Manutenção para instalar.",
        "update_spawn_fail_title": "Não foi possível iniciar a atualização",
        "update_spawn_fail_body": "Nenhum terminal encontrado. Atualize manualmente: git pull e ./install.sh",
        # windows tray
        "win_startup": "Iniciar com o Windows",
        "win_update_manual": "Não foi possível abrir o PowerShell. Atualize manualmente: git pull e .\\install-windows.ps1",
        "dlg_title": "Configurações — Claude Usage",
        "dlg_tab_general": "Geral",
        "dlg_tab_topbar": "Barra superior",
        "dlg_lang": "Idioma",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Atualização (s)",
        "dlg_thresholds": "Limites de alerta (%)",
        "dlg_thresholds_hint": "Separados por vírgula, ex.: 80, 95",
        "dlg_show_claude": "Mostrar o Claude na barra superior",
        "dlg_metric_five_hour": "Sessão 5h",
        "dlg_metric_seven_day": "Semanal 7d",
        "dlg_metric_seven_day_sonnet": "Sonnet 7d",
        "dlg_provider_prefix": "Mostrar o prefixo (C)",
        "dlg_alert_prefix": "Mostrar o prefixo de alerta (/!\\)",
        "dlg_metric_labels": "Rotular cada métrica (5h, 7d)",
        "dlg_compact": "Modo compacto (um único valor)",
        "dlg_metric_separator": "Separador entre métricas",
        "dlg_percent_decimals": "Casas decimais da porcentagem",
        "dlg_tab_accounts": "Contas",
        "dlg_accounts_enabled": "Gerenciar várias contas do Claude",
        "dlg_accounts_enabled_hint": "Memoriza cada conta quando você entra e mostra o uso delas no menu.",
        "dlg_account_switch_enabled": "Permitir trocar de conta (grava em ~/.claude)",
        "dlg_account_switch_hint": "Reescreve as credenciais do Claude Code. Vale na próxima execução do `claude`; pode atrapalhar uma sessão em andamento.",
        "dlg_preview": "Prévia:",
        "dlg_preview_icon_only": "(somente ícone)",
        "dlg_save": "Salvar",
        "dlg_cancel": "Cancelar",
        "dlg_edit_json": "Editar JSON (alertas…)",
        "dlg_save_failed_title": "Não foi possível salvar as configurações",
        "dlg_tab_maintenance": "Manutenção",
        "dlg_version": "Versão: {ver}",
        "dlg_update_uptodate": "Você está atualizado.",
        "dlg_update_available": "Atualização disponível: v{ver}",
        "dlg_update_btn": "Atualizar agora",
        "dlg_sound_menu": "Som (80%)",
        "dlg_tab_sound": "Som",
        "dlg_sound_enabled": "Ativar som a 80% (sessão)",
        "dlg_sound_mode": "Efeito",
        "dlg_sound_mode_kylian": "Kylian ditador",
        "dlg_sound_mode_classic": "Lembrete clássico",
        "dlg_sound_mode_custom": "Personalizado",
        "dlg_sound_custom_audio": "Som personalizado",
        "dlg_sound_custom_image": "Imagem personalizada",
        "dlg_sound_choose_audio": "Escolher som…",
        "dlg_sound_choose_image": "Escolher imagem…",
        "dlg_sound_test": "Testar o alerta",
        "dlg_sound_none": "(nenhum)",
        "dlg_update_check_enabled": "Verificar atualizações ao iniciar",
        "dlg_update_check_hint": "Consulta a API pública do GitHub (nenhum dado ou token é enviado).",
        "dlg_uninstall_btn": "Desinstalar o aplicativo…",
        "dlg_uninstall_confirm_title": "Desinstalar o Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Remove o indicador, a entrada de inicialização automática e os ícones. Um terminal será aberto e o indicador será encerrado.",
        "dlg_uninstall_purge_check": "Também apagar minhas configurações, o histórico e as contas salvas",
        "dlg_footer_uptodate": "v{ver} — atualizado",
        "dlg_footer_update": "Atualização disponível (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Contas do Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token expirado — troque para atualizar",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "indisponível",
        "acct_switch": "Trocar para esta conta",
        "acct_switch_active": "Conta ativa",
        "acct_switch_disabled": "Troca desativada (ver Configurações)",
        "acct_forget": "Esquecer esta conta",
        "acct_switch_confirm_title": "Trocar de conta do Claude?",
        "acct_switch_confirm_body": "O Claude Code usará {email} na próxima execução do `claude`. Uma sessão já aberta não muda em tempo real.",
        "acct_switch_ok_title": "Conta do Claude trocada",
        "acct_switch_ok_body": "{email} será usada na próxima execução do `claude`.",
        "acct_switch_fail_title": "Falha ao trocar de conta",
        "acct_switch_fail_body": "Não foi possível gravar as credenciais (permissões de ~/.claude?).",
        "acct_forget_confirm_title": "Esquecer esta conta?",
        "acct_forget_confirm_body": "{email} será removida da lista e suas credenciais salvas serão apagadas (sem efeito em ~/.claude).",
        # API cost (ccusage — dropdown only, opt-in)
        "cost_menu_title": "Custo da API — {amount} hoje",
        "cost_menu_pending": "Custo da API — …",
        "cost_today": "Hoje: {amount}",
        "cost_7d": "Últimos 7 dias: {amount}",
        "cost_month": "Este mês: {amount}",
        "cost_checked": "Atualizado {when}",
        "cost_stale": "A última atualização falhou — últimos valores",
        "cost_refresh": "Recalcular agora",
        "cost_pending": "Calculando…",
        "dlg_cost_section": "Custo da API (ccusage)",
        "dlg_cost_enabled": "Mostrar o custo da API no menu",
        "dlg_cost_command": "Comando (vazio = detecção automática)",
        "dlg_cost_refresh": "Atualizar a cada (min)",
        "dlg_cost_hint": "Estimado pelo ccusage a partir dos transcripts locais — todos os agentes CLI, não é uma fatura.",
        "dlg_cost_detected": "Detectado: {cmd}",
        "dlg_cost_missing": "Nenhum runner encontrado — instale bun, node ou pnpm",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Conclua o login OAuth no terminal que acabou de abrir.",
        "login_title_fail": "Entrar no Claude Code",
        "login_body_fail": "Nenhum terminal encontrado. Abra um e execute `claude`.",
        "reset_title": "{label} reiniciada",
        "reset_body": "Contador de volta a zero.",
        "threshold_title": "{label} em {util:.0f}%",
        "threshold_body": "Reinicia {abs} (em {rem})",
        "settings_reloaded_title": "Configurações recarregadas",
        "settings_reloaded_body": "Arquivo de configuração aplicado.",
        "alert_fired_title": "Alerta: {label}",
        "alert_fired_body": "+{delta:.1f} pp em {window}h ({metric})",
        "now": "agora",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " sem sessão ",
        "date_format": "%a %d %b %H:%M",
        # terminal attention (attention.py)
        "att_menu_title": "Terminais Claude ({n})",
        "att_state_waiting": "aguarda uma resposta",
        "att_state_done": "tarefa concluída",
        "att_session": "{project} — {state}",
        "att_clear": "Parar o piscar",
        "att_tip_waiting": "{n} a aguardar resposta",
        "att_tip_done": "{n} concluída(s)",
        "dlg_att_section": "Terminais Claude",
        "dlg_att_enabled": "Piscar quando um terminal me espera",
        "dlg_att_hooks_install": "Instalar os hooks do Claude Code",
        "dlg_att_hooks_remove": "Remover os hooks do Claude Code",
        "dlg_att_hooks_ok": "Hooks instalados",
        "dlg_att_hooks_missing": "Hooks em falta — o piscar continua inativo",
        "dlg_att_hooks_confirm_title": "Instalar os hooks do Claude Code?",
        "dlg_att_hooks_confirm_body": "Quatro hooks (Stop, Notification, UserPromptSubmit, SessionEnd) serão adicionados a ~/.claude/settings.json. Os teus hooks atuais não são alterados e é escrita uma cópia em settings.json.cusi-bak.",
        "dlg_att_hooks_failed": "Falhou: {err}",
        "dlg_att_hint": "Os hooks escrevem um marcador por sessão na cache; o ícone pisca enquanto um terminal aguarda.",
        "dlg_att_blink_ms": "Cadência do piscar (ms)",
        # account handoff (handoff.py)
        "ho_busy_title": "Ainda há uma sessão Claude a correr",
        "ho_busy_body": "Estão abertas {n} sessão(ões) do Claude Code. A retoma vai funcionar à mesma: uma sessão viva mantém o token em memória. Mas pode reescrever o ficheiro de credenciais mais tarde, e um próximo arranque usaria a conta antiga. Fecha-a quando puderes.",
        "ho_unknown_body": "Não foi possível verificar se há uma sessão Claude aberta. A retoma vai funcionar, mas uma sessão deixada aberta pode reescrever o ficheiro de credenciais mais tarde.",
        "ho_switch_anyway": "Continuar",
        "ho_resume_menu": "Trocar e retomar em…",
        "ho_no_projects": "Nenhum projeto recente",
        "ho_project_row": "{name}",
        "ho_project_age": "{name}  —  {age}",
        "ho_resume_confirm_title": "Trocar para {email} e retomar?",
        "ho_resume_confirm_body": "A conta ativa passa a ser {email} e abre-se um terminal em {project} com claude --continue para retomar a última conversa dessa pasta.",
        "ho_resume_ok_title": "Troca feita",
        "ho_resume_ok_body": "Terminal aberto em {project} com a conta {email}.",
        "ho_no_binary_title": "Binário claude não encontrado",
        "ho_no_binary_body": "Não foi possível localizar o executável claude. A troca foi feita; executa claude --continue tu mesmo.",
        "ho_launch_fail_title": "Não foi possível abrir um terminal",
        "ho_launch_fail_body": "A troca foi feita, mas o terminal não arrancou. Executa claude --continue em {project}.",
        # limit-reached handoff offer (handoff.pick_offer)
        "ho_offer_row": "Limite atingido — trocar para {email} e retomar {project}",
        "ho_offer_title": "Limite de 5 h atingido",
        "ho_offer_body": "{email} ainda tem margem ({util} %). Abre o menu para trocar e retomar {project}.",
    },
}

_current_lang = DEFAULT_LANG
_missing_keys_warned: set[str] = set()


def detect_lang(settings_lang: str | None = None) -> str:
    """Return the active language. Env > settings > system > default."""
    env = os.environ.get("CLAUDE_USAGE_LANG", "").strip().lower()
    for candidate in (env, (settings_lang or "").strip().lower()):
        if candidate in SUPPORTED_LANGS:
            return candidate
    try:
        sys_lang = (locale.getdefaultlocale()[0] or "").split("_")[0].lower()
    except (ValueError, locale.Error):
        sys_lang = ""
    if sys_lang in SUPPORTED_LANGS:
        return sys_lang
    return DEFAULT_LANG


def set_lang(lang: str) -> None:
    """Set the active language globally."""
    global _current_lang
    if lang in SUPPORTED_LANGS:
        _current_lang = lang
    else:
        _current_lang = DEFAULT_LANG


def current_lang() -> str:
    return _current_lang


def t(key: str, **kwargs: Any) -> str:
    """Look up a translated string. Safe on missing keys."""
    table = STRINGS.get(_current_lang) or STRINGS[DEFAULT_LANG]
    template = table.get(key)
    if template is None:
        template = STRINGS[DEFAULT_LANG].get(key)
    if template is None:
        if key not in _missing_keys_warned:
            _missing_keys_warned.add(key)
            print(f"i18n: missing key {key!r}", file=sys.stderr)
        return key
    if not kwargs:
        return template
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError, ValueError):
        return template


_LOCALE_CANDIDATES = {
    "fr": ("fr_FR.UTF-8", "fr_FR.utf8", "fr_FR", "fr"),
    "en": ("en_US.UTF-8", "en_US.utf8", "en_US", "en_GB.UTF-8", "en"),
    "es": ("es_ES.UTF-8", "es_ES.utf8", "es_ES", "es_MX.UTF-8", "es"),
    "de": ("de_DE.UTF-8", "de_DE.utf8", "de_DE", "de"),
    "ja": ("ja_JP.UTF-8", "ja_JP.utf8", "ja_JP", "ja"),
    "pt": ("pt_BR.UTF-8", "pt_BR.utf8", "pt_BR", "pt_PT.UTF-8", "pt"),
}


def setup_locale(lang: str) -> None:
    """Try to set LC_TIME so strftime localises month/day names.

    Silent fallback to the default C locale if the requested locale isn't
    installed — the user just sees English-looking dates.
    """
    for candidate in _LOCALE_CANDIDATES.get(lang, ()):
        try:
            locale.setlocale(locale.LC_TIME, candidate)
            return
        except locale.Error:
            continue
