"""Internationalised UI strings.

One big dict keyed by language, then by message id. Missing keys fall back
to English (the project's default). Looked up via :func:`t`.

Language resolution order (highest wins):
  1. ``CLAUDE_USAGE_LANG`` env var
  2. ``lang`` field from settings.json
  3. System locale (``locale.getdefaultlocale()``)
  4. ``DEFAULT_LANG``
"""

from __future__ import annotations

import locale
import os
import sys
from typing import Any

DEFAULT_LANG = "en"
SUPPORTED_LANGS = ("en", "fr", "es", "de", "ja", "pt")

# Format placeholders use str.format syntax (``{name}``).
# Keep keys stable — they're referenced from other modules.
STRINGS: dict[str, dict[str, str]] = {
    "fr": {
        # menu items / static
        "not_connected": "non connecté",
        "login_item": "Se connecter à Claude Code",
        "quit": "Quitter",
        "refresh_never": "Rafraîchir  (jamais)",
        "refresh_pending": "Rafraîchir  (…)",
        "refresh_ts": "Rafraîchir  ({ts})",
        "refresh_fail": "Rafraîchir  (échec {ts})",
        "rate_limited": "Rate-limited  (retry dans {d})",
        "open_settings_tip": "Ouvrir {url}",
        "edit_settings": "Réglages…",
        "clear_alerts": "Désactiver les alertes actives",
        "menu_options": "Options",
        # updates
        "update_available": "Mise à jour disponible (v{ver})",
        "update_confirm_title": "Mettre à jour Claude Usage Tab ?",
        "update_confirm_body": "La version v{ver} va être installée (git pull puis réinstallation). Un terminal s'ouvrira et l'indicateur redémarrera.",
        "update_notif_title": "Mise à jour disponible",
        "update_notif_body": "Claude Usage Tab v{ver} est disponible — ouvre les Réglages ▸ Maintenance pour l'installer.",
        "update_spawn_fail_title": "Impossible de lancer la mise à jour",
        "update_spawn_fail_body": "Aucun terminal trouvé. Mets à jour à la main : git pull puis ./install.sh",
        # settings dialog
        "dlg_title": "Réglages — Claude Usage",
        "dlg_tab_general": "Général",
        "dlg_tab_topbar": "Top-bar",
        "dlg_lang": "Langue",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Rafraîchissement (s)",
        "dlg_thresholds": "Seuils d'alerte (%)",
        "dlg_thresholds_hint": "Séparés par des virgules, ex. 80, 95",
        "dlg_show_claude": "Afficher Claude dans la top-bar",
        "dlg_metric_five_hour": "Session 5h",
        "dlg_metric_seven_day": "Hebdo 7j",
        "dlg_metric_seven_day_sonnet": "Sonnet 7j",
        "dlg_provider_prefix": "Afficher le préfixe (C)",
        "dlg_alert_prefix": "Afficher le préfixe d'alerte (/!\\)",
        "dlg_metric_labels": "Étiqueter chaque métrique (5h, 7j)",
        "dlg_compact": "Mode compact (une seule valeur)",
        "dlg_metric_separator": "Séparateur entre métriques",
        "dlg_percent_decimals": "Décimales du pourcentage",
        "dlg_tab_accounts": "Comptes",
        "dlg_accounts_enabled": "Gérer plusieurs comptes Claude",
        "dlg_accounts_enabled_hint": "Mémorise chaque compte quand tu te connectes et affiche leur usage dans le menu.",
        "dlg_account_switch_enabled": "Autoriser le changement de compte (écrit ~/.claude)",
        "dlg_account_switch_hint": "Réécrit les identifiants de Claude Code. Effet au prochain lancement de `claude` ; peut perturber une session en cours.",
        "dlg_preview": "Aperçu :",
        "dlg_preview_icon_only": "(icône seule)",
        "dlg_save": "Enregistrer",
        "dlg_cancel": "Annuler",
        "dlg_edit_json": "Éditer le JSON (alertes…)",
        "dlg_save_failed_title": "Échec de l'enregistrement",
        # maintenance tab + update footer
        "dlg_tab_maintenance": "Maintenance",
        "dlg_version": "Version : {ver}",
        "dlg_update_uptodate": "Vous êtes à jour.",
        "dlg_update_available": "Mise à jour disponible : v{ver}",
        "dlg_update_btn": "Mettre à jour",
        "dlg_sound_80": "Son à 80 % (session)",
        "dlg_sound_80_classic": "Rappel notif classique",
        "dlg_sound_80_kylian": "Kylian dictateur",
        "dlg_sound_80_none": "Rien (silencieux)",
        "dlg_update_check_enabled": "Vérifier les mises à jour au lancement",
        "dlg_update_check_hint": "Interroge l'API publique GitHub (aucune donnée ni token envoyés).",
        "dlg_uninstall_btn": "Désinstaller l'application…",
        "dlg_uninstall_confirm_title": "Désinstaller Claude Usage Tab ?",
        "dlg_uninstall_confirm_body": "Retire l'indicateur, l'entrée de démarrage automatique et les icônes. Un terminal s'ouvrira et l'indicateur s'arrêtera.",
        "dlg_uninstall_purge_check": "Supprimer aussi mes réglages, l'historique et les comptes stockés",
        "dlg_footer_uptodate": "v{ver} — à jour",
        "dlg_footer_update": "Mise à jour disponible (v{ver})",
        # metrics
        "session_5h": "5h",
        "weekly_7d": "7j",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7j  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7j  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        # multi-account (dropdown submenu)
        "accounts_menu": "Comptes Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7j {seven:.0f}%",
        "acct_usage_expired": "token expiré — bascule pour rafraîchir",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "indisponible",
        "acct_switch": "Basculer sur ce compte",
        "acct_switch_active": "Compte actif",
        "acct_switch_disabled": "Changement désactivé (voir Réglages)",
        "acct_forget": "Oublier ce compte",
        "acct_switch_confirm_title": "Basculer de compte Claude ?",
        "acct_switch_confirm_body": "Claude Code utilisera {email} au prochain lancement de `claude`. Une session déjà ouverte ne changera pas à chaud.",
        "acct_switch_ok_title": "Compte Claude changé",
        "acct_switch_ok_body": "{email} sera utilisé au prochain lancement de `claude`.",
        "acct_switch_fail_title": "Échec du changement de compte",
        "acct_switch_fail_body": "Impossible d'écrire les identifiants (permissions de ~/.claude ?).",
        "acct_forget_confirm_title": "Oublier ce compte ?",
        "acct_forget_confirm_body": "{email} sera retiré de la liste et ses identifiants stockés supprimés (aucun effet sur ~/.claude).",
        # notifications
        "login_title_ok": "Claude Code",
        "login_body_ok": "Termine le login OAuth dans le terminal qui vient de s'ouvrir.",
        "login_title_fail": "Se connecter à Claude Code",
        "login_body_fail": "Aucun terminal trouvé. Ouvre-en un et tape `claude`.",
        "reset_title": "{label} réinitialisée",
        "reset_body": "Compteur revenu à zéro.",
        "threshold_title": "{label} à {util:.0f}%",
        "threshold_body": "Reset {abs} (dans {rem})",
        "settings_reloaded_title": "Réglages rechargés",
        "settings_reloaded_body": "Le fichier de config a été appliqué.",
        "alert_fired_title": "Alerte : {label}",
        "alert_fired_body": "+{delta:.1f} pp sur {window}h ({metric})",
        # durations / format_remaining
        "now": "maintenant",
        "dash": "–",
        "duration_days_hours": "{d}j {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        # labels used in top-bar (composed in code by topbar.py)
        # ``label_guide`` is the width-reservation guide string; the
        # status segments below are the non-"ok" states (the ok segment is
        # built dynamically from the selected metrics).
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " non connecté ",
        # date format for strftime
        "date_format": "%a %d %b %H:%M",
    },
    "en": {
        "not_connected": "not signed in",
        "login_item": "Sign in to Claude Code",
        "quit": "Quit",
        "refresh_never": "Refresh  (never)",
        "refresh_pending": "Refresh  (…)",
        "refresh_ts": "Refresh  ({ts})",
        "refresh_fail": "Refresh  (failed {ts})",
        "rate_limited": "Rate-limited  (retry in {d})",
        "open_settings_tip": "Open {url}",
        "edit_settings": "Settings…",
        "clear_alerts": "Clear active alerts",
        "menu_options": "Options",
        # updates
        "update_available": "Update available (v{ver})",
        "update_confirm_title": "Update Claude Usage Tab?",
        "update_confirm_body": "Version v{ver} will be installed (git pull, then reinstall). A terminal will open and the indicator will restart.",
        "update_notif_title": "Update available",
        "update_notif_body": "Claude Usage Tab v{ver} is available — open Settings ▸ Maintenance to install it.",
        "update_spawn_fail_title": "Could not launch the update",
        "update_spawn_fail_body": "No terminal found. Update manually: git pull, then ./install.sh",
        # settings dialog
        "dlg_title": "Settings — Claude Usage",
        "dlg_tab_general": "General",
        "dlg_tab_topbar": "Top-bar",
        "dlg_lang": "Language",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Refresh (s)",
        "dlg_thresholds": "Alert thresholds (%)",
        "dlg_thresholds_hint": "Comma-separated, e.g. 80, 95",
        "dlg_show_claude": "Show Claude in the top-bar",
        "dlg_metric_five_hour": "5h session",
        "dlg_metric_seven_day": "7-day weekly",
        "dlg_metric_seven_day_sonnet": "Sonnet 7-day",
        "dlg_provider_prefix": "Show prefix (C)",
        "dlg_alert_prefix": "Show alert prefix (/!\\)",
        "dlg_metric_labels": "Label each metric (5h, 7d)",
        "dlg_compact": "Compact mode (one value only)",
        "dlg_metric_separator": "Separator between metrics",
        "dlg_percent_decimals": "Percent decimals",
        "dlg_tab_accounts": "Accounts",
        "dlg_accounts_enabled": "Manage multiple Claude accounts",
        "dlg_accounts_enabled_hint": "Remembers each account when you sign in and shows their usage in the menu.",
        "dlg_account_switch_enabled": "Allow switching accounts (writes ~/.claude)",
        "dlg_account_switch_hint": "Rewrites Claude Code credentials. Takes effect on the next `claude` launch; may disrupt a running session.",
        "dlg_preview": "Preview:",
        "dlg_preview_icon_only": "(icon only)",
        "dlg_save": "Save",
        "dlg_cancel": "Cancel",
        "dlg_edit_json": "Edit JSON (alerts…)",
        "dlg_save_failed_title": "Could not save settings",
        # maintenance tab + update footer
        "dlg_tab_maintenance": "Maintenance",
        "dlg_version": "Version: {ver}",
        "dlg_update_uptodate": "You're up to date.",
        "dlg_update_available": "Update available: v{ver}",
        "dlg_update_btn": "Update now",
        "dlg_sound_80": "80% sound (session)",
        "dlg_sound_80_classic": "Classic reminder",
        "dlg_sound_80_kylian": "Kylian dictator",
        "dlg_sound_80_none": "None (silent)",
        "dlg_update_check_enabled": "Check for updates at launch",
        "dlg_update_check_hint": "Queries the public GitHub API (no data or token sent).",
        "dlg_uninstall_btn": "Uninstall the app…",
        "dlg_uninstall_confirm_title": "Uninstall Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Removes the indicator, its autostart entry and its icons. A terminal will open and the indicator will stop.",
        "dlg_uninstall_purge_check": "Also delete my settings, history and stored accounts",
        "dlg_footer_uptodate": "v{ver} — up to date",
        "dlg_footer_update": "Update available (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        # multi-account (dropdown submenu)
        "accounts_menu": "Claude accounts",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token expired — switch to refresh",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "unavailable",
        "acct_switch": "Switch to this account",
        "acct_switch_active": "Active account",
        "acct_switch_disabled": "Switching disabled (see Settings)",
        "acct_forget": "Forget this account",
        "acct_switch_confirm_title": "Switch Claude account?",
        "acct_switch_confirm_body": "Claude Code will use {email} on the next `claude` launch. A running session won't switch live.",
        "acct_switch_ok_title": "Claude account switched",
        "acct_switch_ok_body": "{email} will be used on the next `claude` launch.",
        "acct_switch_fail_title": "Account switch failed",
        "acct_switch_fail_body": "Could not write credentials (~/.claude permissions?).",
        "acct_forget_confirm_title": "Forget this account?",
        "acct_forget_confirm_body": "{email} will be removed from the list and its stored credentials deleted (no effect on ~/.claude).",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Finish the OAuth login in the terminal that just opened.",
        "login_title_fail": "Sign in to Claude Code",
        "login_body_fail": "No terminal found. Open one and run `claude`.",
        "reset_title": "{label} reset",
        "reset_body": "Counter back to zero.",
        "threshold_title": "{label} at {util:.0f}%",
        "threshold_body": "Resets {abs} (in {rem})",
        "settings_reloaded_title": "Settings reloaded",
        "settings_reloaded_body": "Config file applied.",
        "alert_fired_title": "Alert: {label}",
        "alert_fired_body": "+{delta:.1f} pp over {window}h ({metric})",
        "now": "now",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " not signed in ",
        "date_format": "%a %d %b %H:%M",
    },
    "es": {
        "not_connected": "sin sesión",
        "login_item": "Iniciar sesión en Claude Code",
        "quit": "Salir",
        "refresh_never": "Actualizar  (nunca)",
        "refresh_pending": "Actualizar  (…)",
        "refresh_ts": "Actualizar  ({ts})",
        "refresh_fail": "Actualizar  (error {ts})",
        "rate_limited": "Rate-limited  (reintento en {d})",
        "open_settings_tip": "Abrir {url}",
        "edit_settings": "Ajustes…",
        "clear_alerts": "Desactivar las alertas activas",
        "menu_options": "Opciones",
        "update_available": "Actualización disponible (v{ver})",
        "update_confirm_title": "¿Actualizar Claude Usage Tab?",
        "update_confirm_body": "Se instalará la versión v{ver} (git pull y reinstalación). Se abrirá una terminal y el indicador se reiniciará.",
        "update_notif_title": "Actualización disponible",
        "update_notif_body": "Claude Usage Tab v{ver} está disponible — abre Ajustes ▸ Mantenimiento para instalarla.",
        "update_spawn_fail_title": "No se pudo iniciar la actualización",
        "update_spawn_fail_body": "No se encontró ninguna terminal. Actualiza a mano: git pull y ./install.sh",
        "dlg_title": "Ajustes — Claude Usage",
        "dlg_tab_general": "General",
        "dlg_tab_topbar": "Barra superior",
        "dlg_lang": "Idioma",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Actualización (s)",
        "dlg_thresholds": "Umbrales de alerta (%)",
        "dlg_thresholds_hint": "Separados por comas, p. ej. 80, 95",
        "dlg_show_claude": "Mostrar Claude en la barra superior",
        "dlg_metric_five_hour": "Sesión 5h",
        "dlg_metric_seven_day": "Semanal 7d",
        "dlg_metric_seven_day_sonnet": "Sonnet 7d",
        "dlg_provider_prefix": "Mostrar el prefijo (C)",
        "dlg_alert_prefix": "Mostrar el prefijo de alerta (/!\\)",
        "dlg_metric_labels": "Etiquetar cada métrica (5h, 7d)",
        "dlg_compact": "Modo compacto (un solo valor)",
        "dlg_metric_separator": "Separador entre métricas",
        "dlg_percent_decimals": "Decimales del porcentaje",
        "dlg_tab_accounts": "Cuentas",
        "dlg_accounts_enabled": "Gestionar varias cuentas de Claude",
        "dlg_accounts_enabled_hint": "Recuerda cada cuenta cuando inicias sesión y muestra su uso en el menú.",
        "dlg_account_switch_enabled": "Permitir cambiar de cuenta (escribe ~/.claude)",
        "dlg_account_switch_hint": "Reescribe las credenciales de Claude Code. Surte efecto en el próximo arranque de `claude`; puede afectar una sesión en curso.",
        "dlg_preview": "Vista previa:",
        "dlg_preview_icon_only": "(solo icono)",
        "dlg_save": "Guardar",
        "dlg_cancel": "Cancelar",
        "dlg_edit_json": "Editar JSON (alertas…)",
        "dlg_save_failed_title": "No se pudieron guardar los ajustes",
        "dlg_tab_maintenance": "Mantenimiento",
        "dlg_version": "Versión: {ver}",
        "dlg_update_uptodate": "Estás al día.",
        "dlg_update_available": "Actualización disponible: v{ver}",
        "dlg_update_btn": "Actualizar",
        "dlg_sound_80": "Sonido al 80 % (sesión)",
        "dlg_sound_80_classic": "Recordatorio clásico",
        "dlg_sound_80_kylian": "Kylian dictador",
        "dlg_sound_80_none": "Ninguno (silencioso)",
        "dlg_update_check_enabled": "Buscar actualizaciones al iniciar",
        "dlg_update_check_hint": "Consulta la API pública de GitHub (no se envía ningún dato ni token).",
        "dlg_uninstall_btn": "Desinstalar la aplicación…",
        "dlg_uninstall_confirm_title": "¿Desinstalar Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Elimina el indicador, su entrada de arranque automático y sus iconos. Se abrirá una terminal y el indicador se detendrá.",
        "dlg_uninstall_purge_check": "Eliminar también mis ajustes, el historial y las cuentas guardadas",
        "dlg_footer_uptodate": "v{ver} — al día",
        "dlg_footer_update": "Actualización disponible (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Cuentas de Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token caducado — cambia para actualizar",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "no disponible",
        "acct_switch": "Cambiar a esta cuenta",
        "acct_switch_active": "Cuenta activa",
        "acct_switch_disabled": "Cambio desactivado (ver Ajustes)",
        "acct_forget": "Olvidar esta cuenta",
        "acct_switch_confirm_title": "¿Cambiar de cuenta de Claude?",
        "acct_switch_confirm_body": "Claude Code usará {email} en el próximo arranque de `claude`. Una sesión ya abierta no cambiará en caliente.",
        "acct_switch_ok_title": "Cuenta de Claude cambiada",
        "acct_switch_ok_body": "{email} se usará en el próximo arranque de `claude`.",
        "acct_switch_fail_title": "Error al cambiar de cuenta",
        "acct_switch_fail_body": "No se pudieron escribir las credenciales (¿permisos de ~/.claude?).",
        "acct_forget_confirm_title": "¿Olvidar esta cuenta?",
        "acct_forget_confirm_body": "{email} se quitará de la lista y sus credenciales guardadas se borrarán (sin efecto en ~/.claude).",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Termina el inicio de sesión OAuth en la terminal que se acaba de abrir.",
        "login_title_fail": "Iniciar sesión en Claude Code",
        "login_body_fail": "No se encontró ninguna terminal. Abre una y ejecuta `claude`.",
        "reset_title": "{label} reiniciada",
        "reset_body": "Contador de vuelta a cero.",
        "threshold_title": "{label} al {util:.0f}%",
        "threshold_body": "Se reinicia {abs} (en {rem})",
        "settings_reloaded_title": "Ajustes recargados",
        "settings_reloaded_body": "Se aplicó el archivo de configuración.",
        "alert_fired_title": "Alerta: {label}",
        "alert_fired_body": "+{delta:.1f} pp en {window}h ({metric})",
        "now": "ahora",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " sin sesión ",
        "date_format": "%a %d %b %H:%M",
    },
    "de": {
        "not_connected": "nicht angemeldet",
        "login_item": "Bei Claude Code anmelden",
        "quit": "Beenden",
        "refresh_never": "Aktualisieren  (nie)",
        "refresh_pending": "Aktualisieren  (…)",
        "refresh_ts": "Aktualisieren  ({ts})",
        "refresh_fail": "Aktualisieren  (Fehler {ts})",
        "rate_limited": "Rate-limited  (erneut in {d})",
        "open_settings_tip": "{url} öffnen",
        "edit_settings": "Einstellungen…",
        "clear_alerts": "Aktive Warnungen deaktivieren",
        "menu_options": "Optionen",
        "update_available": "Update verfügbar (v{ver})",
        "update_confirm_title": "Claude Usage Tab aktualisieren?",
        "update_confirm_body": "Version v{ver} wird installiert (git pull, dann Neuinstallation). Ein Terminal öffnet sich und der Indikator startet neu.",
        "update_notif_title": "Update verfügbar",
        "update_notif_body": "Claude Usage Tab v{ver} ist verfügbar — öffne Einstellungen ▸ Wartung, um es zu installieren.",
        "update_spawn_fail_title": "Update konnte nicht gestartet werden",
        "update_spawn_fail_body": "Kein Terminal gefunden. Manuell aktualisieren: git pull, dann ./install.sh",
        "dlg_title": "Einstellungen — Claude Usage",
        "dlg_tab_general": "Allgemein",
        "dlg_tab_topbar": "Menüleiste",
        "dlg_lang": "Sprache",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Aktualisierung (s)",
        "dlg_thresholds": "Warnschwellen (%)",
        "dlg_thresholds_hint": "Komma-getrennt, z. B. 80, 95",
        "dlg_show_claude": "Claude in der Menüleiste anzeigen",
        "dlg_metric_five_hour": "5h-Sitzung",
        "dlg_metric_seven_day": "Woche 7T",
        "dlg_metric_seven_day_sonnet": "Sonnet 7T",
        "dlg_provider_prefix": "Präfix anzeigen (C)",
        "dlg_alert_prefix": "Warn-Präfix anzeigen (/!\\)",
        "dlg_metric_labels": "Jede Metrik beschriften (5h, 7T)",
        "dlg_compact": "Kompaktmodus (nur ein Wert)",
        "dlg_metric_separator": "Trennzeichen zwischen Metriken",
        "dlg_percent_decimals": "Nachkommastellen (Prozent)",
        "dlg_tab_accounts": "Konten",
        "dlg_accounts_enabled": "Mehrere Claude-Konten verwalten",
        "dlg_accounts_enabled_hint": "Merkt sich jedes Konto beim Anmelden und zeigt dessen Nutzung im Menü.",
        "dlg_account_switch_enabled": "Kontowechsel erlauben (schreibt ~/.claude)",
        "dlg_account_switch_hint": "Überschreibt die Claude-Code-Anmeldedaten. Wirkt beim nächsten `claude`-Start; kann eine laufende Sitzung stören.",
        "dlg_preview": "Vorschau:",
        "dlg_preview_icon_only": "(nur Symbol)",
        "dlg_save": "Speichern",
        "dlg_cancel": "Abbrechen",
        "dlg_edit_json": "JSON bearbeiten (Warnungen…)",
        "dlg_save_failed_title": "Einstellungen konnten nicht gespeichert werden",
        "dlg_tab_maintenance": "Wartung",
        "dlg_version": "Version: {ver}",
        "dlg_update_uptodate": "Du bist auf dem neuesten Stand.",
        "dlg_update_available": "Update verfügbar: v{ver}",
        "dlg_update_btn": "Jetzt aktualisieren",
        "dlg_sound_80": "Ton bei 80 % (Sitzung)",
        "dlg_sound_80_classic": "Klassische Erinnerung",
        "dlg_sound_80_kylian": "Kylian-Diktator",
        "dlg_sound_80_none": "Keiner (stumm)",
        "dlg_update_check_enabled": "Beim Start nach Updates suchen",
        "dlg_update_check_hint": "Fragt die öffentliche GitHub-API ab (keine Daten oder Tokens gesendet).",
        "dlg_uninstall_btn": "App deinstallieren…",
        "dlg_uninstall_confirm_title": "Claude Usage Tab deinstallieren?",
        "dlg_uninstall_confirm_body": "Entfernt den Indikator, seinen Autostart-Eintrag und seine Symbole. Ein Terminal öffnet sich und der Indikator wird beendet.",
        "dlg_uninstall_purge_check": "Auch meine Einstellungen, den Verlauf und gespeicherte Konten löschen",
        "dlg_footer_uptodate": "v{ver} — aktuell",
        "dlg_footer_update": "Update verfügbar (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7T",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7T  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7T  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Claude-Konten",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7T {seven:.0f}%",
        "acct_usage_expired": "Token abgelaufen — wechseln zum Aktualisieren",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "nicht verfügbar",
        "acct_switch": "Zu diesem Konto wechseln",
        "acct_switch_active": "Aktives Konto",
        "acct_switch_disabled": "Wechsel deaktiviert (siehe Einstellungen)",
        "acct_forget": "Dieses Konto vergessen",
        "acct_switch_confirm_title": "Claude-Konto wechseln?",
        "acct_switch_confirm_body": "Claude Code verwendet {email} beim nächsten `claude`-Start. Eine bereits laufende Sitzung wechselt nicht live.",
        "acct_switch_ok_title": "Claude-Konto gewechselt",
        "acct_switch_ok_body": "{email} wird beim nächsten `claude`-Start verwendet.",
        "acct_switch_fail_title": "Kontowechsel fehlgeschlagen",
        "acct_switch_fail_body": "Anmeldedaten konnten nicht geschrieben werden (Rechte von ~/.claude?).",
        "acct_forget_confirm_title": "Dieses Konto vergessen?",
        "acct_forget_confirm_body": "{email} wird aus der Liste entfernt und die gespeicherten Anmeldedaten gelöscht (keine Auswirkung auf ~/.claude).",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Schließe die OAuth-Anmeldung im gerade geöffneten Terminal ab.",
        "login_title_fail": "Bei Claude Code anmelden",
        "login_body_fail": "Kein Terminal gefunden. Öffne eines und führe `claude` aus.",
        "reset_title": "{label} zurückgesetzt",
        "reset_body": "Zähler wieder auf null.",
        "threshold_title": "{label} bei {util:.0f}%",
        "threshold_body": "Zurücksetzung {abs} (in {rem})",
        "settings_reloaded_title": "Einstellungen neu geladen",
        "settings_reloaded_body": "Konfigurationsdatei angewendet.",
        "alert_fired_title": "Warnung: {label}",
        "alert_fired_body": "+{delta:.1f} pp über {window}h ({metric})",
        "now": "jetzt",
        "dash": "–",
        "duration_days_hours": "{d}T {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " nicht angemeldet ",
        "date_format": "%a %d %b %H:%M",
    },
    "ja": {
        "not_connected": "未接続",
        "login_item": "Claude Code にサインイン",
        "quit": "終了",
        "refresh_never": "更新  (未実行)",
        "refresh_pending": "更新  (…)",
        "refresh_ts": "更新  ({ts})",
        "refresh_fail": "更新  (失敗 {ts})",
        "rate_limited": "Rate-limited  (再試行 {d})",
        "open_settings_tip": "{url} を開く",
        "edit_settings": "設定…",
        "clear_alerts": "有効なアラートを解除",
        "menu_options": "オプション",
        "update_available": "アップデートあり (v{ver})",
        "update_confirm_title": "Claude Usage Tab を更新しますか？",
        "update_confirm_body": "バージョン v{ver} をインストールします（git pull 後に再インストール）。ターミナルが開き、インジケーターが再起動します。",
        "update_notif_title": "アップデートあり",
        "update_notif_body": "Claude Usage Tab v{ver} が利用可能です — 設定 ▸ メンテナンス から更新できます。",
        "update_spawn_fail_title": "アップデートを起動できませんでした",
        "update_spawn_fail_body": "ターミナルが見つかりません。手動で更新してください: git pull 後に ./install.sh",
        "dlg_title": "設定 — Claude Usage",
        "dlg_tab_general": "一般",
        "dlg_tab_topbar": "メニューバー",
        "dlg_lang": "言語",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "更新間隔 (秒)",
        "dlg_thresholds": "アラートしきい値 (%)",
        "dlg_thresholds_hint": "カンマ区切り、例: 80, 95",
        "dlg_show_claude": "メニューバーに Claude を表示",
        "dlg_metric_five_hour": "5時間セッション",
        "dlg_metric_seven_day": "週間 7日",
        "dlg_metric_seven_day_sonnet": "Sonnet 7日",
        "dlg_provider_prefix": "接頭辞を表示 (C)",
        "dlg_alert_prefix": "アラート接頭辞を表示 (/!\\)",
        "dlg_metric_labels": "各指標にラベルを付ける (5h, 7d)",
        "dlg_compact": "コンパクト表示（1つの値のみ）",
        "dlg_metric_separator": "指標間の区切り文字",
        "dlg_percent_decimals": "パーセントの小数点以下桁数",
        "dlg_tab_accounts": "アカウント",
        "dlg_accounts_enabled": "複数の Claude アカウントを管理",
        "dlg_accounts_enabled_hint": "サインインするたびに各アカウントを記憶し、その使用状況をメニューに表示します。",
        "dlg_account_switch_enabled": "アカウント切り替えを許可 (~/.claude に書き込み)",
        "dlg_account_switch_hint": "Claude Code の認証情報を書き換えます。次回の `claude` 起動時に反映され、実行中のセッションに影響する場合があります。",
        "dlg_preview": "プレビュー:",
        "dlg_preview_icon_only": "(アイコンのみ)",
        "dlg_save": "保存",
        "dlg_cancel": "キャンセル",
        "dlg_edit_json": "JSON を編集 (アラート…)",
        "dlg_save_failed_title": "設定を保存できませんでした",
        "dlg_tab_maintenance": "メンテナンス",
        "dlg_version": "バージョン: {ver}",
        "dlg_update_uptodate": "最新の状態です。",
        "dlg_update_available": "アップデートあり: v{ver}",
        "dlg_update_btn": "今すぐ更新",
        "dlg_sound_80": "80% の通知音（セッション）",
        "dlg_sound_80_classic": "クラシックな通知音",
        "dlg_sound_80_kylian": "キリアン独裁者",
        "dlg_sound_80_none": "なし（無音）",
        "dlg_update_check_enabled": "起動時にアップデートを確認",
        "dlg_update_check_hint": "GitHub の公開 API に問い合わせます（データやトークンは送信しません）。",
        "dlg_uninstall_btn": "アプリをアンインストール…",
        "dlg_uninstall_confirm_title": "Claude Usage Tab をアンインストールしますか？",
        "dlg_uninstall_confirm_body": "インジケーター、自動起動エントリ、アイコンを削除します。ターミナルが開き、インジケーターが停止します。",
        "dlg_uninstall_purge_check": "設定・履歴・保存済みアカウントも削除する",
        "dlg_footer_uptodate": "v{ver} — 最新",
        "dlg_footer_update": "アップデートあり (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Claude アカウント",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "トークン期限切れ — 切り替えて更新",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "利用不可",
        "acct_switch": "このアカウントに切り替え",
        "acct_switch_active": "アクティブなアカウント",
        "acct_switch_disabled": "切り替えは無効です（設定を参照）",
        "acct_forget": "このアカウントを削除",
        "acct_switch_confirm_title": "Claude アカウントを切り替えますか？",
        "acct_switch_confirm_body": "次回の `claude` 起動時に Claude Code は {email} を使用します。実行中のセッションはその場では切り替わりません。",
        "acct_switch_ok_title": "Claude アカウントを切り替えました",
        "acct_switch_ok_body": "次回の `claude` 起動時に {email} が使用されます。",
        "acct_switch_fail_title": "アカウントの切り替えに失敗",
        "acct_switch_fail_body": "認証情報を書き込めませんでした（~/.claude の権限を確認）。",
        "acct_forget_confirm_title": "このアカウントを削除しますか？",
        "acct_forget_confirm_body": "{email} をリストから削除し、保存された認証情報を消去します（~/.claude には影響しません）。",
        "login_title_ok": "Claude Code",
        "login_body_ok": "開いたターミナルで OAuth ログインを完了してください。",
        "login_title_fail": "Claude Code にサインイン",
        "login_body_fail": "ターミナルが見つかりません。ターミナルを開いて `claude` を実行してください。",
        "reset_title": "{label} をリセットしました",
        "reset_body": "カウンターがゼロに戻りました。",
        "threshold_title": "{label} が {util:.0f}%",
        "threshold_body": "リセット {abs}（{rem}後）",
        "settings_reloaded_title": "設定を再読み込みしました",
        "settings_reloaded_body": "設定ファイルを適用しました。",
        "alert_fired_title": "アラート: {label}",
        "alert_fired_body": "+{delta:.1f} pp / {window}h ({metric})",
        "now": "今",
        "dash": "–",
        "duration_days_hours": "{d}日{h}時間",
        "duration_hours_minutes": "{h}時間{m:02d}分",
        "duration_minutes": "{m}分",
        "duration_seconds": "{s}秒",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " 未接続 ",
        "date_format": "%a %d %b %H:%M",
    },
    "pt": {
        "not_connected": "sem sessão",
        "login_item": "Entrar no Claude Code",
        "quit": "Sair",
        "refresh_never": "Atualizar  (nunca)",
        "refresh_pending": "Atualizar  (…)",
        "refresh_ts": "Atualizar  ({ts})",
        "refresh_fail": "Atualizar  (falha {ts})",
        "rate_limited": "Rate-limited  (nova tentativa em {d})",
        "open_settings_tip": "Abrir {url}",
        "edit_settings": "Configurações…",
        "clear_alerts": "Desativar os alertas ativos",
        "menu_options": "Opções",
        "update_available": "Atualização disponível (v{ver})",
        "update_confirm_title": "Atualizar o Claude Usage Tab?",
        "update_confirm_body": "A versão v{ver} será instalada (git pull e reinstalação). Um terminal será aberto e o indicador reiniciará.",
        "update_notif_title": "Atualização disponível",
        "update_notif_body": "Claude Usage Tab v{ver} está disponível — abra Configurações ▸ Manutenção para instalar.",
        "update_spawn_fail_title": "Não foi possível iniciar a atualização",
        "update_spawn_fail_body": "Nenhum terminal encontrado. Atualize manualmente: git pull e ./install.sh",
        "dlg_title": "Configurações — Claude Usage",
        "dlg_tab_general": "Geral",
        "dlg_tab_topbar": "Barra superior",
        "dlg_lang": "Idioma",
        "dlg_lang_fr": "Français",
        "dlg_lang_en": "English",
        "dlg_lang_es": "Español",
        "dlg_lang_de": "Deutsch",
        "dlg_lang_ja": "日本語",
        "dlg_lang_pt": "Português (BR)",
        "dlg_poll": "Atualização (s)",
        "dlg_thresholds": "Limites de alerta (%)",
        "dlg_thresholds_hint": "Separados por vírgula, ex.: 80, 95",
        "dlg_show_claude": "Mostrar o Claude na barra superior",
        "dlg_metric_five_hour": "Sessão 5h",
        "dlg_metric_seven_day": "Semanal 7d",
        "dlg_metric_seven_day_sonnet": "Sonnet 7d",
        "dlg_provider_prefix": "Mostrar o prefixo (C)",
        "dlg_alert_prefix": "Mostrar o prefixo de alerta (/!\\)",
        "dlg_metric_labels": "Rotular cada métrica (5h, 7d)",
        "dlg_compact": "Modo compacto (um único valor)",
        "dlg_metric_separator": "Separador entre métricas",
        "dlg_percent_decimals": "Casas decimais da porcentagem",
        "dlg_tab_accounts": "Contas",
        "dlg_accounts_enabled": "Gerenciar várias contas do Claude",
        "dlg_accounts_enabled_hint": "Memoriza cada conta quando você entra e mostra o uso delas no menu.",
        "dlg_account_switch_enabled": "Permitir trocar de conta (grava em ~/.claude)",
        "dlg_account_switch_hint": "Reescreve as credenciais do Claude Code. Vale na próxima execução do `claude`; pode atrapalhar uma sessão em andamento.",
        "dlg_preview": "Prévia:",
        "dlg_preview_icon_only": "(somente ícone)",
        "dlg_save": "Salvar",
        "dlg_cancel": "Cancelar",
        "dlg_edit_json": "Editar JSON (alertas…)",
        "dlg_save_failed_title": "Não foi possível salvar as configurações",
        "dlg_tab_maintenance": "Manutenção",
        "dlg_version": "Versão: {ver}",
        "dlg_update_uptodate": "Você está atualizado.",
        "dlg_update_available": "Atualização disponível: v{ver}",
        "dlg_update_btn": "Atualizar agora",
        "dlg_sound_80": "Som a 80% (sessão)",
        "dlg_sound_80_classic": "Lembrete clássico",
        "dlg_sound_80_kylian": "Kylian ditador",
        "dlg_sound_80_none": "Nenhum (silencioso)",
        "dlg_update_check_enabled": "Verificar atualizações ao iniciar",
        "dlg_update_check_hint": "Consulta a API pública do GitHub (nenhum dado ou token é enviado).",
        "dlg_uninstall_btn": "Desinstalar o aplicativo…",
        "dlg_uninstall_confirm_title": "Desinstalar o Claude Usage Tab?",
        "dlg_uninstall_confirm_body": "Remove o indicador, a entrada de inicialização automática e os ícones. Um terminal será aberto e o indicador será encerrado.",
        "dlg_uninstall_purge_check": "Também apagar minhas configurações, o histórico e as contas salvas",
        "dlg_footer_uptodate": "v{ver} — atualizado",
        "dlg_footer_update": "Atualização disponível (v{ver})",
        "session_5h": "5h",
        "weekly_7d": "7d",
        "sonnet_7d": "S7",
        "session_line": "  5h  [{bar}] {util:3.0f}%  ↳ {rem}",
        "weekly_line": "  7d  [{bar}] {util:3.0f}%  ↳ {rem}",
        "sonnet_line": "  S7  [{bar}] {util:3.0f}%",
        "session_placeholder": "  5h  …",
        "weekly_placeholder": "  7d  …",
        "sonnet_placeholder": "  S7  …",
        "extra_active": "  $$  {used}/{limit} {currency}",
        "accounts_menu": "Contas do Claude",
        "acct_active_mark": "●",
        "acct_inactive_mark": "○",
        "acct_usage": "5h {five:.0f}% · 7d {seven:.0f}%",
        "acct_usage_expired": "token expirado — troque para atualizar",
        "acct_usage_rl": "rate-limited",
        "acct_usage_error": "indisponível",
        "acct_switch": "Trocar para esta conta",
        "acct_switch_active": "Conta ativa",
        "acct_switch_disabled": "Troca desativada (ver Configurações)",
        "acct_forget": "Esquecer esta conta",
        "acct_switch_confirm_title": "Trocar de conta do Claude?",
        "acct_switch_confirm_body": "O Claude Code usará {email} na próxima execução do `claude`. Uma sessão já aberta não muda em tempo real.",
        "acct_switch_ok_title": "Conta do Claude trocada",
        "acct_switch_ok_body": "{email} será usada na próxima execução do `claude`.",
        "acct_switch_fail_title": "Falha ao trocar de conta",
        "acct_switch_fail_body": "Não foi possível gravar as credenciais (permissões de ~/.claude?).",
        "acct_forget_confirm_title": "Esquecer esta conta?",
        "acct_forget_confirm_body": "{email} será removida da lista e suas credenciais salvas serão apagadas (sem efeito em ~/.claude).",
        "login_title_ok": "Claude Code",
        "login_body_ok": "Conclua o login OAuth no terminal que acabou de abrir.",
        "login_title_fail": "Entrar no Claude Code",
        "login_body_fail": "Nenhum terminal encontrado. Abra um e execute `claude`.",
        "reset_title": "{label} reiniciada",
        "reset_body": "Contador de volta a zero.",
        "threshold_title": "{label} em {util:.0f}%",
        "threshold_body": "Reinicia {abs} (em {rem})",
        "settings_reloaded_title": "Configurações recarregadas",
        "settings_reloaded_body": "Arquivo de configuração aplicado.",
        "alert_fired_title": "Alerta: {label}",
        "alert_fired_body": "+{delta:.1f} pp em {window}h ({metric})",
        "now": "agora",
        "dash": "–",
        "duration_days_hours": "{d}d {h}h",
        "duration_hours_minutes": "{h}h{m:02d}",
        "duration_minutes": "{m}min",
        "duration_seconds": "{s}s",
        "label_placeholder": " …",
        "label_guide": " /!\\ C 99% . 99% . 99% ",
        "label_seg_claude_rl": "C !RL",
        "label_seg_claude_err": "C !ERR",
        "label_alert_prefix": "/!\\",
        "label_not_connected": " sem sessão ",
        "date_format": "%a %d %b %H:%M",
    },
}

_current_lang = DEFAULT_LANG
_missing_keys_warned: set[str] = set()


def detect_lang(settings_lang: str | None = None) -> str:
    """Return the active language. Env > settings > system > default."""
    env = os.environ.get("CLAUDE_USAGE_LANG", "").strip().lower()
    for candidate in (env, (settings_lang or "").strip().lower()):
        if candidate in SUPPORTED_LANGS:
            return candidate
    try:
        sys_lang = (locale.getdefaultlocale()[0] or "").split("_")[0].lower()
    except (ValueError, locale.Error):
        sys_lang = ""
    if sys_lang in SUPPORTED_LANGS:
        return sys_lang
    return DEFAULT_LANG


def set_lang(lang: str) -> None:
    """Set the active language globally."""
    global _current_lang
    if lang in SUPPORTED_LANGS:
        _current_lang = lang
    else:
        _current_lang = DEFAULT_LANG


def current_lang() -> str:
    return _current_lang


def t(key: str, **kwargs: Any) -> str:
    """Look up a translated string. Safe on missing keys."""
    table = STRINGS.get(_current_lang) or STRINGS[DEFAULT_LANG]
    template = table.get(key)
    if template is None:
        template = STRINGS[DEFAULT_LANG].get(key)
    if template is None:
        if key not in _missing_keys_warned:
            _missing_keys_warned.add(key)
            print(f"i18n: missing key {key!r}", file=sys.stderr)
        return key
    if not kwargs:
        return template
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError, ValueError):
        return template


_LOCALE_CANDIDATES = {
    "fr": ("fr_FR.UTF-8", "fr_FR.utf8", "fr_FR", "fr"),
    "en": ("en_US.UTF-8", "en_US.utf8", "en_US", "en_GB.UTF-8", "en"),
    "es": ("es_ES.UTF-8", "es_ES.utf8", "es_ES", "es_MX.UTF-8", "es"),
    "de": ("de_DE.UTF-8", "de_DE.utf8", "de_DE", "de"),
    "ja": ("ja_JP.UTF-8", "ja_JP.utf8", "ja_JP", "ja"),
    "pt": ("pt_BR.UTF-8", "pt_BR.utf8", "pt_BR", "pt_PT.UTF-8", "pt"),
}


def setup_locale(lang: str) -> None:
    """Try to set LC_TIME so strftime localises month/day names.

    Silent fallback to the default C locale if the requested locale isn't
    installed — the user just sees English-looking dates.
    """
    for candidate in _LOCALE_CANDIDATES.get(lang, ()):
        try:
            locale.setlocale(locale.LC_TIME, candidate)
            return
        except locale.Error:
            continue
